-- ================================================================
-- PARAGUAY LOCATIONS DATA (266 cities)
-- ================================================================
-- This is shared/master data for all stores
-- Run this AFTER migration 090_carrier_coverage_system.sql
-- ================================================================

INSERT INTO paraguay_locations (city, department, zone_code, city_normalized, department_normalized) VALUES
    ('Asunción', 'ASUNCION', 'ASUNCION', 'asuncion', 'asuncion'),
    ('Bahía Negra', 'ALTO PARAGUAY', 'INTERIOR_2', 'bahia negra', 'alto paraguay'),
    ('Capitán Carmelo Peralta', 'ALTO PARAGUAY', 'INTERIOR_2', 'capitan carmelo peralta', 'alto paraguay'),
    ('Fuerte Olimpo', 'ALTO PARAGUAY', 'INTERIOR_2', 'fuerte olimpo', 'alto paraguay'),
    ('Puerto Casado', 'ALTO PARAGUAY', 'INTERIOR_2', 'puerto casado', 'alto paraguay'),
    ('Ciudad del Este', 'ALTO PARANA', 'INTERIOR_1', 'ciudad del este', 'alto parana'),
    ('Doctor Juan León Mallorquín', 'ALTO PARANA', 'INTERIOR_2', 'doctor juan leon mallorquin', 'alto parana'),
    ('Doctor Raúl Peña', 'ALTO PARANA', 'INTERIOR_2', 'doctor raul pena', 'alto parana'),
    ('Domingo Martínez de Irala', 'ALTO PARANA', 'INTERIOR_2', 'domingo martinez de irala', 'alto parana'),
    ('Hernandarias', 'ALTO PARANA', 'INTERIOR_1', 'hernandarias', 'alto parana'),
    ('Iruña', 'ALTO PARANA', 'INTERIOR_2', 'iruna', 'alto parana'),
    ('Itakyry', 'ALTO PARANA', 'INTERIOR_2', 'itakyry', 'alto parana'),
    ('Juan Emilio O''Leary', 'ALTO PARANA', 'INTERIOR_2', 'juan emilio o''leary', 'alto parana'),
    ('Los Cedrales', 'ALTO PARANA', 'INTERIOR_2', 'los cedrales', 'alto parana'),
    ('Mbaracayú', 'ALTO PARANA', 'INTERIOR_2', 'mbaracayu', 'alto parana'),
    ('Minga Guazú', 'ALTO PARANA', 'INTERIOR_1', 'minga guazu', 'alto parana'),
    ('Minga Porá', 'ALTO PARANA', 'INTERIOR_2', 'minga pora', 'alto parana'),
    ('Naranjal', 'ALTO PARANA', 'INTERIOR_2', 'naranjal', 'alto parana'),
    ('Ñacunday', 'ALTO PARANA', 'INTERIOR_2', 'nacunday', 'alto parana'),
    ('Presidente Franco', 'ALTO PARANA', 'INTERIOR_1', 'presidente franco', 'alto parana'),
    ('San Alberto', 'ALTO PARANA', 'INTERIOR_2', 'san alberto', 'alto parana'),
    ('San Cristóbal', 'ALTO PARANA', 'INTERIOR_2', 'san cristobal', 'alto parana'),
    ('Santa Fe del Paraná', 'ALTO PARANA', 'INTERIOR_2', 'santa fe del parana', 'alto parana'),
    ('Santa Rita', 'ALTO PARANA', 'INTERIOR_1', 'santa rita', 'alto parana'),
    ('Santa Rosa del Monday', 'ALTO PARANA', 'INTERIOR_2', 'santa rosa del monday', 'alto parana'),
    ('Tavapy', 'ALTO PARANA', 'INTERIOR_2', 'tavapy', 'alto parana'),
    ('Yguazú', 'ALTO PARANA', 'INTERIOR_2', 'yguazu', 'alto parana'),
    ('Bella Vista Norte', 'AMAMBAY', 'INTERIOR_2', 'bella vista norte', 'amambay'),
    ('Capitán Bado', 'AMAMBAY', 'INTERIOR_2', 'capitan bado', 'amambay'),
    ('Cerro Cora', 'AMAMBAY', 'INTERIOR_2', 'cerro cora', 'amambay'),
    ('Karapaí', 'AMAMBAY', 'INTERIOR_2', 'karapai', 'amambay'),
    ('Pedro Juan Caballero', 'AMAMBAY', 'INTERIOR_1', 'pedro juan caballero', 'amambay'),
    ('Zanja Pyta', 'AMAMBAY', 'INTERIOR_2', 'zanja pyta', 'amambay'),
    ('Boquerón', 'BOQUERON', 'INTERIOR_2', 'boqueron', 'boqueron'),
    ('Filadelfia', 'BOQUERON', 'INTERIOR_2', 'filadelfia', 'boqueron'),
    ('Loma Plata', 'BOQUERON', 'INTERIOR_2', 'loma plata', 'boqueron'),
    ('Mariscal José Félix Estigarribia', 'BOQUERON', 'INTERIOR_2', 'mariscal jose felix estigarribia', 'boqueron'),
    ('3 de febrero', 'CAAGUAZU', 'INTERIOR_2', '3 de febrero', 'caaguazu'),
    ('Caaguazú', 'CAAGUAZU', 'INTERIOR_1', 'caaguazu', 'caaguazu'),
    ('Carayao', 'CAAGUAZU', 'INTERIOR_2', 'carayao', 'caaguazu'),
    ('Coronel Oviedo', 'CAAGUAZU', 'INTERIOR_1', 'coronel oviedo', 'caaguazu'),
    ('Dr. Cecilio Baez', 'CAAGUAZU', 'INTERIOR_2', 'dr. cecilio baez', 'caaguazu'),
    ('Dr. J. Eulogio Estigarribia', 'CAAGUAZU', 'INTERIOR_2', 'dr. j. eulogio estigarribia', 'caaguazu'),
    ('Dr. Juan Manuel Frutos', 'CAAGUAZU', 'INTERIOR_2', 'dr. juan manuel frutos', 'caaguazu'),
    ('Jose Domingo Ocampos', 'CAAGUAZU', 'INTERIOR_1', 'jose domingo ocampos', 'caaguazu'),
    ('La Pastora', 'CAAGUAZU', 'INTERIOR_2', 'la pastora', 'caaguazu'),
    ('Mcal. Francisco Solano Lopez', 'CAAGUAZU', 'INTERIOR_2', 'mcal. francisco solano lopez', 'caaguazu'),
    ('Nueva Londres', 'CAAGUAZU', 'INTERIOR_2', 'nueva londres', 'caaguazu'),
    ('Nueva Toledo', 'CAAGUAZU', 'INTERIOR_2', 'nueva toledo', 'caaguazu'),
    ('R.I. 3 Corrales', 'CAAGUAZU', 'INTERIOR_2', 'r.i. 3 corrales', 'caaguazu'),
    ('Raul Arsenio Oviedo', 'CAAGUAZU', 'INTERIOR_2', 'raul arsenio oviedo', 'caaguazu'),
    ('Repatriacion', 'CAAGUAZU', 'INTERIOR_2', 'repatriacion', 'caaguazu'),
    ('San Joaquin', 'CAAGUAZU', 'INTERIOR_2', 'san joaquin', 'caaguazu'),
    ('San Jose de los Arroyos', 'CAAGUAZU', 'INTERIOR_2', 'san jose de los arroyos', 'caaguazu'),
    ('Santa Rosa del Mbutuy', 'CAAGUAZU', 'INTERIOR_2', 'santa rosa del mbutuy', 'caaguazu'),
    ('Simon Bolivar', 'CAAGUAZU', 'INTERIOR_2', 'simon bolivar', 'caaguazu'),
    ('Tembiapora', 'CAAGUAZU', 'INTERIOR_2', 'tembiapora', 'caaguazu'),
    ('Vaqueria', 'CAAGUAZU', 'INTERIOR_2', 'vaqueria', 'caaguazu'),
    ('Yhu', 'CAAGUAZU', 'INTERIOR_2', 'yhu', 'caaguazu'),
    ('3 de mayo', 'CAAZAPA', 'INTERIOR_2', '3 de mayo', 'caazapa'),
    ('Abai', 'CAAZAPA', 'INTERIOR_2', 'abai', 'caazapa'),
    ('Buena Vista', 'CAAZAPA', 'INTERIOR_2', 'buena vista', 'caazapa'),
    ('Caazapá', 'CAAZAPA', 'INTERIOR_2', 'caazapa', 'caazapa'),
    ('Coronel Maciel', 'CAAZAPA', 'INTERIOR_2', 'coronel maciel', 'caazapa'),
    ('Doctor Moises S. Bertoni', 'CAAZAPA', 'INTERIOR_2', 'doctor moises s. bertoni', 'caazapa'),
    ('Fulgencio Yegros', 'CAAZAPA', 'INTERIOR_2', 'fulgencio yegros', 'caazapa'),
    ('General Higinio Morínigo', 'CAAZAPA', 'INTERIOR_2', 'general higinio morinigo', 'caazapa'),
    ('San Juan Nepomuceno', 'CAAZAPA', 'INTERIOR_2', 'san juan nepomuceno', 'caazapa'),
    ('Tavaí', 'CAAZAPA', 'INTERIOR_2', 'tavai', 'caazapa'),
    ('Yuty', 'CAAZAPA', 'INTERIOR_2', 'yuty', 'caazapa'),
    ('Corpus Christi', 'CANINDEYU', 'INTERIOR_2', 'corpus christi', 'canindeyu'),
    ('Curuguaty', 'CANINDEYU', 'INTERIOR_2', 'curuguaty', 'canindeyu'),
    ('Gral. Francisco Caballero Álvarez', 'CANINDEYU', 'INTERIOR_2', 'gral. francisco caballero alvarez', 'canindeyu'),
    ('Itanará', 'CANINDEYU', 'INTERIOR_2', 'itanara', 'canindeyu'),
    ('Katueté', 'CANINDEYU', 'INTERIOR_2', 'katuete', 'canindeyu'),
    ('La Paloma', 'CANINDEYU', 'INTERIOR_2', 'la paloma', 'canindeyu'),
    ('Maracaná', 'CANINDEYU', 'INTERIOR_2', 'maracana', 'canindeyu'),
    ('Pto. Adela', 'CANINDEYU', 'INTERIOR_2', 'pto. adela', 'canindeyu'),
    ('Laurel', 'CANINDEYU', 'INTERIOR_2', 'laurel', 'canindeyu'),
    ('Nueva Esperanza', 'CANINDEYU', 'INTERIOR_2', 'nueva esperanza', 'canindeyu'),
    ('Salto del Guaira', 'CANINDEYU', 'INTERIOR_2', 'salto del guaira', 'canindeyu'),
    ('Villa Ygatimí', 'CANINDEYU', 'INTERIOR_2', 'villa ygatimi', 'canindeyu'),
    ('Yasy Cañy', 'CANINDEYU', 'INTERIOR_2', 'yasy cany', 'canindeyu'),
    ('Yby Pyta', 'CANINDEYU', 'INTERIOR_2', 'yby pyta', 'canindeyu'),
    ('Ypejhú', 'CANINDEYU', 'INTERIOR_2', 'ypejhu', 'canindeyu'),
    ('Ybyrarobaná', 'CANINDEYU', 'INTERIOR_2', 'ybyrarobana', 'canindeyu'),
    ('Areguá', 'CENTRAL', 'CENTRAL', 'aregua', 'central'),
    ('Capiatá', 'CENTRAL', 'CENTRAL', 'capiata', 'central'),
    ('Fernando de la Mora', 'CENTRAL', 'CENTRAL', 'fernando de la mora', 'central'),
    ('Guarambaré', 'CENTRAL', 'CENTRAL', 'guarambare', 'central'),
    ('Itá', 'CENTRAL', 'CENTRAL', 'ita', 'central'),
    ('Itauguá', 'CENTRAL', 'CENTRAL', 'itaugua', 'central'),
    ('J. Augusto Saldivar', 'CENTRAL', 'CENTRAL', 'j. augusto saldivar', 'central'),
    ('Lambaré', 'CENTRAL', 'CENTRAL', 'lambare', 'central'),
    ('Limpio', 'CENTRAL', 'CENTRAL', 'limpio', 'central'),
    ('Luque', 'CENTRAL', 'CENTRAL', 'luque', 'central'),
    ('Mariano Roque Alonso', 'CENTRAL', 'CENTRAL', 'mariano roque alonso', 'central'),
    ('Nueva Italia', 'CENTRAL', 'CENTRAL', 'nueva italia', 'central'),
    ('Ñemby', 'CENTRAL', 'CENTRAL', 'nemby', 'central'),
    ('San Antonio', 'CENTRAL', 'CENTRAL', 'san antonio', 'central'),
    ('San Lorenzo', 'CENTRAL', 'CENTRAL', 'san lorenzo', 'central'),
    ('Villa Elisa', 'CENTRAL', 'CENTRAL', 'villa elisa', 'central'),
    ('Villeta', 'CENTRAL', 'CENTRAL', 'villeta', 'central'),
    ('Ypacaraí', 'CENTRAL', 'CENTRAL', 'ypacarai', 'central'),
    ('Ypané', 'CENTRAL', 'CENTRAL', 'ypane', 'central'),
    ('Arroyito', 'CONCEPCION', 'INTERIOR_2', 'arroyito', 'concepcion'),
    ('Azote''y', 'CONCEPCION', 'INTERIOR_2', 'azote''y', 'concepcion'),
    ('Belén', 'CONCEPCION', 'INTERIOR_2', 'belen', 'concepcion'),
    ('Concepción', 'CONCEPCION', 'INTERIOR_2', 'concepcion', 'concepcion'),
    ('Horqueta', 'CONCEPCION', 'INTERIOR_2', 'horqueta', 'concepcion'),
    ('Loreto', 'CONCEPCION', 'INTERIOR_2', 'loreto', 'concepcion'),
    ('Paso Barreto', 'CONCEPCION', 'INTERIOR_2', 'paso barreto', 'concepcion'),
    ('Paso Horqueta', 'CONCEPCION', 'INTERIOR_2', 'paso horqueta', 'concepcion'),
    ('San Alfredo', 'CONCEPCION', 'INTERIOR_2', 'san alfredo', 'concepcion'),
    ('San Lázaro', 'CONCEPCION', 'INTERIOR_2', 'san lazaro', 'concepcion'),
    ('San Carlos del Apa', 'CONCEPCION', 'INTERIOR_2', 'san carlos del apa', 'concepcion'),
    ('Sargento Jose Felix Lopez', 'CONCEPCION', 'INTERIOR_2', 'sargento jose felix lopez', 'concepcion'),
    ('Yby Yaú', 'CONCEPCION', 'INTERIOR_2', 'yby yau', 'concepcion'),
    ('Altos', 'CORDILLERA', 'INTERIOR_1', 'altos', 'cordillera'),
    ('Arroyos y Esteros', 'CORDILLERA', 'INTERIOR_2', 'arroyos y esteros', 'cordillera'),
    ('Atyrá', 'CORDILLERA', 'INTERIOR_2', 'atyra', 'cordillera'),
    ('Caacupé', 'CORDILLERA', 'INTERIOR_1', 'caacupe', 'cordillera'),
    ('Caraguatay', 'CORDILLERA', 'INTERIOR_2', 'caraguatay', 'cordillera'),
    ('Emboscada', 'CORDILLERA', 'INTERIOR_2', 'emboscada', 'cordillera'),
    ('Eusebio Ayala', 'CORDILLERA', 'INTERIOR_2', 'eusebio ayala', 'cordillera'),
    ('Isla Pucú', 'CORDILLERA', 'INTERIOR_2', 'isla pucu', 'cordillera'),
    ('Itacurubí de la Cordillera', 'CORDILLERA', 'INTERIOR_2', 'itacurubi de la cordillera', 'cordillera'),
    ('Juan de Mena', 'CORDILLERA', 'INTERIOR_2', 'juan de mena', 'cordillera'),
    ('Loma Grande', 'CORDILLERA', 'INTERIOR_2', 'loma grande', 'cordillera'),
    ('Mbocayaty del Yhaguy', 'CORDILLERA', 'INTERIOR_2', 'mbocayaty del yhaguy', 'cordillera'),
    ('Nueva Colombia', 'CORDILLERA', 'INTERIOR_2', 'nueva colombia', 'cordillera'),
    ('Piribebuy', 'CORDILLERA', 'INTERIOR_1', 'piribebuy', 'cordillera'),
    ('Primero de Marzo', 'CORDILLERA', 'INTERIOR_2', 'primero de marzo', 'cordillera'),
    ('San Bernardino', 'CORDILLERA', 'INTERIOR_1', 'san bernardino', 'cordillera'),
    ('San José Obrero', 'CORDILLERA', 'INTERIOR_2', 'san jose obrero', 'cordillera'),
    ('Santa Elena', 'CORDILLERA', 'INTERIOR_2', 'santa elena', 'cordillera'),
    ('Tobatí', 'CORDILLERA', 'INTERIOR_2', 'tobati', 'cordillera'),
    ('Valenzuela', 'CORDILLERA', 'INTERIOR_2', 'valenzuela', 'cordillera'),
    ('Coronel Martinez', 'GUAIRA', 'INTERIOR_2', 'coronel martinez', 'guaira'),
    ('Borja', 'GUAIRA', 'INTERIOR_2', 'borja', 'guaira'),
    ('Doctor Botrell', 'GUAIRA', 'INTERIOR_2', 'doctor botrell', 'guaira'),
    ('Eugenio A. Garay', 'GUAIRA', 'INTERIOR_2', 'eugenio a. garay', 'guaira'),
    ('Félix Pérez Cardozo', 'GUAIRA', 'INTERIOR_2', 'felix perez cardozo', 'guaira'),
    ('Independencia', 'GUAIRA', 'INTERIOR_2', 'independencia', 'guaira'),
    ('Itapé', 'GUAIRA', 'INTERIOR_2', 'itape', 'guaira'),
    ('Iturbe', 'GUAIRA', 'INTERIOR_2', 'iturbe', 'guaira'),
    ('José Fassardi', 'GUAIRA', 'INTERIOR_2', 'jose fassardi', 'guaira'),
    ('Jose Mauricio Troche', 'GUAIRA', 'INTERIOR_2', 'jose mauricio troche', 'guaira'),
    ('Mbocayaty del Guairá', 'GUAIRA', 'INTERIOR_2', 'mbocayaty del guaira', 'guaira'),
    ('Natalicio Talavera', 'GUAIRA', 'INTERIOR_2', 'natalicio talavera', 'guaira'),
    ('Ñumi', 'GUAIRA', 'INTERIOR_2', 'numi', 'guaira'),
    ('Paso Yobai', 'GUAIRA', 'INTERIOR_2', 'paso yobai', 'guaira'),
    ('San Salvador', 'GUAIRA', 'INTERIOR_2', 'san salvador', 'guaira'),
    ('Tebicuary', 'GUAIRA', 'INTERIOR_2', 'tebicuary', 'guaira'),
    ('Villarrica', 'GUAIRA', 'INTERIOR_1', 'villarrica', 'guaira'),
    ('Yataity', 'GUAIRA', 'INTERIOR_2', 'yataity', 'guaira'),
    ('Alto Vera', 'ITAPUA', 'INTERIOR_2', 'alto vera', 'itapua'),
    ('Bella Vista', 'ITAPUA', 'INTERIOR_2', 'bella vista', 'itapua'),
    ('Cambyreta', 'ITAPUA', 'INTERIOR_2', 'cambyreta', 'itapua'),
    ('Capitan Meza', 'ITAPUA', 'INTERIOR_2', 'capitan meza', 'itapua'),
    ('Capitan Miranda', 'ITAPUA', 'INTERIOR_2', 'capitan miranda', 'itapua'),
    ('Carlos Antonio López', 'ITAPUA', 'INTERIOR_2', 'carlos antonio lopez', 'itapua'),
    ('Carmen del Parana', 'ITAPUA', 'INTERIOR_2', 'carmen del parana', 'itapua'),
    ('Coronel Bogado', 'ITAPUA', 'INTERIOR_2', 'coronel bogado', 'itapua'),
    ('Edelira', 'ITAPUA', 'INTERIOR_2', 'edelira', 'itapua'),
    ('Encarnación', 'ITAPUA', 'INTERIOR_1', 'encarnacion', 'itapua'),
    ('Fram', 'ITAPUA', 'INTERIOR_2', 'fram', 'itapua'),
    ('General Jose Maria Delgado', 'ITAPUA', 'INTERIOR_2', 'general jose maria delgado', 'itapua'),
    ('Gral. Artigas', 'ITAPUA', 'INTERIOR_2', 'gral. artigas', 'itapua'),
    ('Hohenau', 'ITAPUA', 'INTERIOR_2', 'hohenau', 'itapua'),
    ('Itapua Poty', 'ITAPUA', 'INTERIOR_2', 'itapua poty', 'itapua'),
    ('Jesús de Tavarangué', 'ITAPUA', 'INTERIOR_2', 'jesus de tavarangue', 'itapua'),
    ('Jose Leandro Oviedo', 'ITAPUA', 'INTERIOR_2', 'jose leandro oviedo', 'itapua'),
    ('La Paz', 'ITAPUA', 'INTERIOR_2', 'la paz', 'itapua'),
    ('Mayor Otaño', 'ITAPUA', 'INTERIOR_2', 'mayor otano', 'itapua'),
    ('Natalio', 'ITAPUA', 'INTERIOR_2', 'natalio', 'itapua'),
    ('Nueva Alborada', 'ITAPUA', 'INTERIOR_2', 'nueva alborada', 'itapua'),
    ('Obligado', 'ITAPUA', 'INTERIOR_2', 'obligado', 'itapua'),
    ('Pirapo', 'ITAPUA', 'INTERIOR_2', 'pirapo', 'itapua'),
    ('San Cosme y Damián', 'ITAPUA', 'INTERIOR_2', 'san cosme y damian', 'itapua'),
    ('San Juan del Paraná', 'ITAPUA', 'INTERIOR_2', 'san juan del parana', 'itapua'),
    ('San Pedro del Paraná', 'ITAPUA', 'INTERIOR_2', 'san pedro del parana', 'itapua'),
    ('San Rafael del Parana', 'ITAPUA', 'INTERIOR_2', 'san rafael del parana', 'itapua'),
    ('Tomas R. Pereira', 'ITAPUA', 'INTERIOR_2', 'tomas r. pereira', 'itapua'),
    ('Trinidad', 'ITAPUA', 'INTERIOR_2', 'trinidad', 'itapua'),
    ('Yatytay', 'ITAPUA', 'INTERIOR_2', 'yatytay', 'itapua'),
    ('Ayolas', 'MISIONES', 'INTERIOR_2', 'ayolas', 'misiones'),
    ('San Ignacio Guazú', 'MISIONES', 'INTERIOR_2', 'san ignacio guazu', 'misiones'),
    ('San Juan Bautista', 'MISIONES', 'INTERIOR_2', 'san juan bautista', 'misiones'),
    ('San Miguel', 'MISIONES', 'INTERIOR_2', 'san miguel', 'misiones'),
    ('San Patricio', 'MISIONES', 'INTERIOR_2', 'san patricio', 'misiones'),
    ('Santa María de Fé', 'MISIONES', 'INTERIOR_2', 'santa maria de fe', 'misiones'),
    ('Santa Rosa Misiones', 'MISIONES', 'INTERIOR_2', 'santa rosa misiones', 'misiones'),
    ('Santiago', 'MISIONES', 'INTERIOR_2', 'santiago', 'misiones'),
    ('Villa Florida', 'MISIONES', 'INTERIOR_2', 'villa florida', 'misiones'),
    ('Yabebyry', 'MISIONES', 'INTERIOR_2', 'yabebyry', 'misiones'),
    ('Alberdi', 'ÑEEMBUCU', 'INTERIOR_2', 'alberdi', 'neembucu'),
    ('Cerrito', 'ÑEEMBUCU', 'INTERIOR_2', 'cerrito', 'neembucu'),
    ('Desmochados', 'ÑEEMBUCU', 'INTERIOR_2', 'desmochados', 'neembucu'),
    ('Gral. José E. Díaz', 'ÑEEMBUCU', 'INTERIOR_2', 'gral. jose e. diaz', 'neembucu'),
    ('Guazucuá', 'ÑEEMBUCU', 'INTERIOR_2', 'guazucua', 'neembucu'),
    ('Humaitá', 'ÑEEMBUCU', 'INTERIOR_2', 'humaita', 'neembucu'),
    ('Isla Umbú', 'ÑEEMBUCU', 'INTERIOR_2', 'isla umbu', 'neembucu'),
    ('Laureles', 'ÑEEMBUCU', 'INTERIOR_2', 'laureles', 'neembucu'),
    ('Mayor José D. Martínez', 'ÑEEMBUCU', 'INTERIOR_2', 'mayor jose d. martinez', 'neembucu'),
    ('Paso de Patria', 'ÑEEMBUCU', 'INTERIOR_2', 'paso de patria', 'neembucu'),
    ('Pilar', 'ÑEEMBUCU', 'INTERIOR_2', 'pilar', 'neembucu'),
    ('San Juan Bautista del Ñeembucú', 'ÑEEMBUCU', 'INTERIOR_2', 'san juan bautista del neembucu', 'neembucu'),
    ('Tacuaras', 'ÑEEMBUCU', 'INTERIOR_2', 'tacuaras', 'neembucu'),
    ('Villa Franca', 'ÑEEMBUCU', 'INTERIOR_2', 'villa franca', 'neembucu'),
    ('Villa Oliva', 'ÑEEMBUCU', 'INTERIOR_2', 'villa oliva', 'neembucu'),
    ('Villalbin', 'ÑEEMBUCU', 'INTERIOR_2', 'villalbin', 'neembucu'),
    ('Acahay', 'PARAGUARI', 'INTERIOR_2', 'acahay', 'paraguari'),
    ('Caapucú', 'PARAGUARI', 'INTERIOR_2', 'caapucu', 'paraguari'),
    ('Carapeguá', 'PARAGUARI', 'INTERIOR_2', 'carapegua', 'paraguari'),
    ('Escobar', 'PARAGUARI', 'INTERIOR_2', 'escobar', 'paraguari'),
    ('Gral. Bernardino Caballero', 'PARAGUARI', 'INTERIOR_2', 'gral. bernardino caballero', 'paraguari'),
    ('La Colmena', 'PARAGUARI', 'INTERIOR_2', 'la colmena', 'paraguari'),
    ('María Antonia', 'PARAGUARI', 'INTERIOR_2', 'maria antonia', 'paraguari'),
    ('Mbuyapey', 'PARAGUARI', 'INTERIOR_2', 'mbuyapey', 'paraguari'),
    ('Paraguarí', 'PARAGUARI', 'INTERIOR_2', 'paraguari', 'paraguari'),
    ('Pirayú', 'PARAGUARI', 'INTERIOR_2', 'pirayu', 'paraguari'),
    ('Quiindy', 'PARAGUARI', 'INTERIOR_2', 'quiindy', 'paraguari'),
    ('Quyquyhó', 'PARAGUARI', 'INTERIOR_2', 'quyquyho', 'paraguari'),
    ('San Roque González de Santa Cruz', 'PARAGUARI', 'INTERIOR_2', 'san roque gonzalez de santa cruz', 'paraguari'),
    ('Sapucai', 'PARAGUARI', 'INTERIOR_2', 'sapucai', 'paraguari'),
    ('Tebicuarymí', 'PARAGUARI', 'INTERIOR_2', 'tebicuarymi', 'paraguari'),
    ('Yaguarón', 'PARAGUARI', 'INTERIOR_2', 'yaguaron', 'paraguari'),
    ('Ybycuí', 'PARAGUARI', 'INTERIOR_2', 'ybycui', 'paraguari'),
    ('Ybytymí', 'PARAGUARI', 'INTERIOR_2', 'ybytymi', 'paraguari'),
    ('Benjamin Aceval', 'PRESIDENTE HAYES', 'INTERIOR_2', 'benjamin aceval', 'presidente hayes'),
    ('Campo Aceval', 'PRESIDENTE HAYES', 'INTERIOR_2', 'campo aceval', 'presidente hayes'),
    ('Gral. Jose Maria Bruguez', 'PRESIDENTE HAYES', 'INTERIOR_2', 'gral. jose maria bruguez', 'presidente hayes'),
    ('José Falcón', 'PRESIDENTE HAYES', 'INTERIOR_2', 'jose falcon', 'presidente hayes'),
    ('Nueva Asunción', 'PRESIDENTE HAYES', 'INTERIOR_2', 'nueva asuncion', 'presidente hayes'),
    ('Nanawa', 'PRESIDENTE HAYES', 'INTERIOR_2', 'nanawa', 'presidente hayes'),
    ('Puerto Pinasco', 'PRESIDENTE HAYES', 'INTERIOR_2', 'puerto pinasco', 'presidente hayes'),
    ('Tte. 1ro Manuel Irala Fernandez', 'PRESIDENTE HAYES', 'INTERIOR_2', 'tte. 1ro manuel irala fernandez', 'presidente hayes'),
    ('Tte. Esteban Martinez', 'PRESIDENTE HAYES', 'INTERIOR_2', 'tte. esteban martinez', 'presidente hayes'),
    ('Villa Hayes', 'PRESIDENTE HAYES', 'INTERIOR_2', 'villa hayes', 'presidente hayes'),
    ('25 de diciembre', 'SAN PEDRO', 'INTERIOR_2', '25 de diciembre', 'san pedro'),
    ('Antequera', 'SAN PEDRO', 'INTERIOR_2', 'antequera', 'san pedro'),
    ('Capiibary', 'SAN PEDRO', 'INTERIOR_2', 'capiibary', 'san pedro'),
    ('Choré', 'SAN PEDRO', 'INTERIOR_2', 'chore', 'san pedro'),
    ('Gral. Elizardo Aquino', 'SAN PEDRO', 'INTERIOR_2', 'gral. elizardo aquino', 'san pedro'),
    ('Gral. Resquín', 'SAN PEDRO', 'INTERIOR_2', 'gral. resquin', 'san pedro'),
    ('Guayaibí', 'SAN PEDRO', 'INTERIOR_2', 'guayaibi', 'san pedro'),
    ('Itacurubí del Rosario', 'SAN PEDRO', 'INTERIOR_2', 'itacurubi del rosario', 'san pedro'),
    ('Liberación', 'SAN PEDRO', 'INTERIOR_2', 'liberacion', 'san pedro'),
    ('Lima', 'SAN PEDRO', 'INTERIOR_2', 'lima', 'san pedro'),
    ('Nueva Germania', 'SAN PEDRO', 'INTERIOR_2', 'nueva germania', 'san pedro'),
    ('San Estanislao', 'SAN PEDRO', 'INTERIOR_2', 'san estanislao', 'san pedro'),
    ('San Pablo', 'SAN PEDRO', 'INTERIOR_2', 'san pablo', 'san pedro'),
    ('San Pedro de Ycuamandyyu', 'SAN PEDRO', 'INTERIOR_2', 'san pedro de ycuamandyyu', 'san pedro'),
    ('San Vicente Pancholo', 'SAN PEDRO', 'INTERIOR_2', 'san vicente pancholo', 'san pedro'),
    ('Santa Rosa del Aguaray', 'SAN PEDRO', 'INTERIOR_2', 'santa rosa del aguaray', 'san pedro'),
    ('Tacuatí', 'SAN PEDRO', 'INTERIOR_2', 'tacuati', 'san pedro'),
    ('Unión', 'SAN PEDRO', 'INTERIOR_2', 'union', 'san pedro'),
    ('Villa del Rosario', 'SAN PEDRO', 'INTERIOR_2', 'villa del rosario', 'san pedro'),
    ('Yataity del Norte', 'SAN PEDRO', 'INTERIOR_2', 'yataity del norte', 'san pedro'),
    ('Yrybucuá', 'SAN PEDRO', 'INTERIOR_2', 'yrybucua', 'san pedro'),
    ('San José del Rosario', 'SAN PEDRO', 'INTERIOR_2', 'san jose del rosario', 'san pedro'),
    ('Puerto Vallemi', 'CONCEPCION', 'INTERIOR_2', 'puerto vallemi', 'concepcion'),
    ('San Ignacio', 'MISIONES', 'INTERIOR_2', 'san ignacio', 'misiones'),
    ('Maria Auxiliadora', 'MISIONES', 'INTERIOR_2', 'maria auxiliadora', 'misiones'),
    ('Puente Kyha', 'CANINDEYU', 'INTERIOR_2', 'puente kyha', 'canindeyu')
ON CONFLICT (city, department) DO UPDATE SET
    zone_code = EXCLUDED.zone_code,
    city_normalized = EXCLUDED.city_normalized,
    department_normalized = EXCLUDED.department_normalized;

-- Total: 266 locations inserted/updated
