-- ================================================================
-- CARRIER COVERAGE DATA FOR NOCTE, BEHIPNOS, BIOVITALIDAD
-- ================================================================
-- INSTRUCTIONS:
-- 1. First, create the carriers in each store (via UI or SQL)
-- 2. Replace the placeholder UUIDs with actual carrier IDs
-- 3. Run this script for each store
-- ================================================================

-- STEP 1: Create carriers (run for each store)
-- Replace STORE_ID_HERE with the actual store UUID

/*
INSERT INTO carriers (store_id, name, phone, is_active) VALUES
    ('STORE_ID_HERE', 'Lucero del este', NULL, TRUE),
    ('STORE_ID_HERE', 'ANDRES COURIER', NULL, TRUE),
    ('STORE_ID_HERE', 'REINALDO COURIER', NULL, TRUE),
    ('STORE_ID_HERE', 'WERAHA', NULL, TRUE);
*/

-- STEP 2: Import coverage data
-- This uses a temporary table approach for easier management

-- Create temp table with coverage data
CREATE TEMP TABLE temp_carrier_coverage (
    carrier_name VARCHAR(100),
    city VARCHAR(150),
    rate DECIMAL(12,2)
);

INSERT INTO temp_carrier_coverage (carrier_name, city, rate) VALUES
    ('Lucero del este', 'Asunción', 25000),
    ('ANDRES COURIER', 'Asunción', 18000),
    ('REINALDO COURIER', 'Asunción', 18000),
    ('WERAHA', 'Asunción', 24000),
    ('Lucero del este', 'Bahía Negra', NULL),
    ('ANDRES COURIER', 'Bahía Negra', NULL),
    ('REINALDO COURIER', 'Bahía Negra', NULL),
    ('WERAHA', 'Bahía Negra', NULL),
    ('Lucero del este', 'Capitán Carmelo Peralta', NULL),
    ('ANDRES COURIER', 'Capitán Carmelo Peralta', NULL),
    ('REINALDO COURIER', 'Capitán Carmelo Peralta', NULL),
    ('WERAHA', 'Capitán Carmelo Peralta', NULL),
    ('Lucero del este', 'Fuerte Olimpo', NULL),
    ('ANDRES COURIER', 'Fuerte Olimpo', NULL),
    ('REINALDO COURIER', 'Fuerte Olimpo', NULL),
    ('WERAHA', 'Fuerte Olimpo', NULL),
    ('Lucero del este', 'Puerto Casado', NULL),
    ('ANDRES COURIER', 'Puerto Casado', NULL),
    ('REINALDO COURIER', 'Puerto Casado', NULL),
    ('WERAHA', 'Puerto Casado', NULL),
    ('Lucero del este', 'Ciudad del Este', 20000),
    ('ANDRES COURIER', 'Ciudad del Este', NULL),
    ('REINALDO COURIER', 'Ciudad del Este', NULL),
    ('WERAHA', 'Ciudad del Este', NULL),
    ('Lucero del este', 'Doctor Juan León Mallorquín', 30000),
    ('ANDRES COURIER', 'Doctor Juan León Mallorquín', NULL),
    ('REINALDO COURIER', 'Doctor Juan León Mallorquín', NULL),
    ('WERAHA', 'Doctor Juan León Mallorquín', NULL),
    ('Lucero del este', 'Doctor Raúl Peña', NULL),
    ('ANDRES COURIER', 'Doctor Raúl Peña', NULL),
    ('REINALDO COURIER', 'Doctor Raúl Peña', NULL),
    ('WERAHA', 'Doctor Raúl Peña', NULL),
    ('Lucero del este', 'Domingo Martínez de Irala', NULL),
    ('ANDRES COURIER', 'Domingo Martínez de Irala', NULL),
    ('REINALDO COURIER', 'Domingo Martínez de Irala', NULL),
    ('WERAHA', 'Domingo Martínez de Irala', NULL),
    ('Lucero del este', 'Hernandarias', 25000),
    ('ANDRES COURIER', 'Hernandarias', NULL),
    ('REINALDO COURIER', 'Hernandarias', NULL),
    ('WERAHA', 'Hernandarias', NULL),
    ('Lucero del este', 'Iruña', NULL),
    ('ANDRES COURIER', 'Iruña', NULL),
    ('REINALDO COURIER', 'Iruña', NULL),
    ('WERAHA', 'Iruña', NULL),
    ('Lucero del este', 'Itakyry', NULL),
    ('ANDRES COURIER', 'Itakyry', NULL),
    ('REINALDO COURIER', 'Itakyry', NULL),
    ('WERAHA', 'Itakyry', NULL),
    ('Lucero del este', 'Juan Emilio O''Leary', 30000),
    ('ANDRES COURIER', 'Juan Emilio O''Leary', NULL),
    ('REINALDO COURIER', 'Juan Emilio O''Leary', NULL),
    ('WERAHA', 'Juan Emilio O''Leary', NULL),
    ('Lucero del este', 'Los Cedrales', 35000),
    ('ANDRES COURIER', 'Los Cedrales', NULL),
    ('REINALDO COURIER', 'Los Cedrales', NULL),
    ('WERAHA', 'Los Cedrales', NULL),
    ('Lucero del este', 'Mbaracayú', NULL),
    ('ANDRES COURIER', 'Mbaracayú', NULL),
    ('REINALDO COURIER', 'Mbaracayú', NULL),
    ('WERAHA', 'Mbaracayú', NULL),
    ('Lucero del este', 'Minga Guazú', 30000),
    ('ANDRES COURIER', 'Minga Guazú', NULL),
    ('REINALDO COURIER', 'Minga Guazú', NULL),
    ('WERAHA', 'Minga Guazú', NULL),
    ('Lucero del este', 'Minga Porá', 35000),
    ('ANDRES COURIER', 'Minga Porá', NULL),
    ('REINALDO COURIER', 'Minga Porá', NULL),
    ('WERAHA', 'Minga Porá', NULL),
    ('Lucero del este', 'Naranjal', 35000),
    ('ANDRES COURIER', 'Naranjal', NULL),
    ('REINALDO COURIER', 'Naranjal', NULL),
    ('WERAHA', 'Naranjal', NULL),
    ('Lucero del este', 'Ñacunday', NULL),
    ('ANDRES COURIER', 'Ñacunday', NULL),
    ('REINALDO COURIER', 'Ñacunday', NULL),
    ('WERAHA', 'Ñacunday', NULL),
    ('Lucero del este', 'Presidente Franco', 25000),
    ('ANDRES COURIER', 'Presidente Franco', NULL),
    ('REINALDO COURIER', 'Presidente Franco', NULL),
    ('WERAHA', 'Presidente Franco', NULL),
    ('Lucero del este', 'San Alberto', 35000),
    ('ANDRES COURIER', 'San Alberto', NULL),
    ('REINALDO COURIER', 'San Alberto', NULL),
    ('WERAHA', 'San Alberto', NULL),
    ('Lucero del este', 'San Cristóbal', NULL),
    ('ANDRES COURIER', 'San Cristóbal', NULL),
    ('REINALDO COURIER', 'San Cristóbal', NULL),
    ('WERAHA', 'San Cristóbal', NULL),
    ('Lucero del este', 'Santa Fe del Paraná', 35000),
    ('ANDRES COURIER', 'Santa Fe del Paraná', NULL),
    ('REINALDO COURIER', 'Santa Fe del Paraná', NULL),
    ('WERAHA', 'Santa Fe del Paraná', NULL),
    ('Lucero del este', 'Santa Rita', 35000),
    ('ANDRES COURIER', 'Santa Rita', NULL),
    ('REINALDO COURIER', 'Santa Rita', NULL),
    ('WERAHA', 'Santa Rita', NULL),
    ('Lucero del este', 'Santa Rosa del Monday', 35000),
    ('ANDRES COURIER', 'Santa Rosa del Monday', NULL),
    ('REINALDO COURIER', 'Santa Rosa del Monday', NULL),
    ('WERAHA', 'Santa Rosa del Monday', NULL),
    ('Lucero del este', 'Tavapy', 35000),
    ('ANDRES COURIER', 'Tavapy', NULL),
    ('REINALDO COURIER', 'Tavapy', NULL),
    ('WERAHA', 'Tavapy', NULL),
    ('Lucero del este', 'Yguazú', 35000),
    ('ANDRES COURIER', 'Yguazú', NULL),
    ('REINALDO COURIER', 'Yguazú', NULL),
    ('WERAHA', 'Yguazú', NULL),
    ('Lucero del este', 'Bella Vista Norte', NULL),
    ('ANDRES COURIER', 'Bella Vista Norte', NULL),
    ('REINALDO COURIER', 'Bella Vista Norte', NULL),
    ('WERAHA', 'Bella Vista Norte', NULL),
    ('Lucero del este', 'Capitán Bado', NULL),
    ('ANDRES COURIER', 'Capitán Bado', NULL),
    ('REINALDO COURIER', 'Capitán Bado', NULL),
    ('WERAHA', 'Capitán Bado', NULL),
    ('Lucero del este', 'Cerro Cora', NULL),
    ('ANDRES COURIER', 'Cerro Cora', NULL),
    ('REINALDO COURIER', 'Cerro Cora', NULL),
    ('WERAHA', 'Cerro Cora', NULL),
    ('Lucero del este', 'Karapaí', NULL),
    ('ANDRES COURIER', 'Karapaí', NULL),
    ('REINALDO COURIER', 'Karapaí', NULL),
    ('WERAHA', 'Karapaí', NULL),
    ('Lucero del este', 'Pedro Juan Caballero', 45000),
    ('ANDRES COURIER', 'Pedro Juan Caballero', NULL),
    ('REINALDO COURIER', 'Pedro Juan Caballero', NULL),
    ('WERAHA', 'Pedro Juan Caballero', NULL),
    ('Lucero del este', 'Zanja Pyta', NULL),
    ('ANDRES COURIER', 'Zanja Pyta', NULL),
    ('REINALDO COURIER', 'Zanja Pyta', NULL),
    ('WERAHA', 'Zanja Pyta', NULL),
    ('Lucero del este', 'Boquerón', NULL),
    ('ANDRES COURIER', 'Boquerón', NULL),
    ('REINALDO COURIER', 'Boquerón', NULL),
    ('WERAHA', 'Boquerón', NULL),
    ('Lucero del este', 'Filadelfia', NULL),
    ('ANDRES COURIER', 'Filadelfia', NULL),
    ('REINALDO COURIER', 'Filadelfia', NULL),
    ('WERAHA', 'Filadelfia', NULL),
    ('Lucero del este', 'Loma Plata', NULL),
    ('ANDRES COURIER', 'Loma Plata', NULL),
    ('REINALDO COURIER', 'Loma Plata', NULL),
    ('WERAHA', 'Loma Plata', NULL),
    ('Lucero del este', 'Mariscal José Félix Estigarribia', NULL),
    ('ANDRES COURIER', 'Mariscal José Félix Estigarribia', NULL),
    ('REINALDO COURIER', 'Mariscal José Félix Estigarribia', NULL),
    ('WERAHA', 'Mariscal José Félix Estigarribia', NULL),
    ('Lucero del este', '3 de febrero', NULL),
    ('ANDRES COURIER', '3 de febrero', NULL),
    ('REINALDO COURIER', '3 de febrero', NULL),
    ('WERAHA', '3 de febrero', NULL),
    ('Lucero del este', 'Caaguazú', 30000),
    ('ANDRES COURIER', 'Caaguazú', NULL),
    ('REINALDO COURIER', 'Caaguazú', NULL),
    ('WERAHA', 'Caaguazú', NULL),
    ('Lucero del este', 'Carayao', NULL),
    ('ANDRES COURIER', 'Carayao', NULL),
    ('REINALDO COURIER', 'Carayao', NULL),
    ('WERAHA', 'Carayao', NULL),
    ('Lucero del este', 'Coronel Oviedo', 35000),
    ('ANDRES COURIER', 'Coronel Oviedo', NULL),
    ('REINALDO COURIER', 'Coronel Oviedo', NULL),
    ('WERAHA', 'Coronel Oviedo', NULL),
    ('Lucero del este', 'Dr. Cecilio Baez', NULL),
    ('ANDRES COURIER', 'Dr. Cecilio Baez', NULL),
    ('REINALDO COURIER', 'Dr. Cecilio Baez', NULL),
    ('WERAHA', 'Dr. Cecilio Baez', NULL),
    ('Lucero del este', 'Dr. J. Eulogio Estigarribia', 35000),
    ('ANDRES COURIER', 'Dr. J. Eulogio Estigarribia', NULL),
    ('REINALDO COURIER', 'Dr. J. Eulogio Estigarribia', NULL),
    ('WERAHA', 'Dr. J. Eulogio Estigarribia', NULL),
    ('Lucero del este', 'Dr. Juan Manuel Frutos', 35000),
    ('ANDRES COURIER', 'Dr. Juan Manuel Frutos', NULL),
    ('REINALDO COURIER', 'Dr. Juan Manuel Frutos', NULL),
    ('WERAHA', 'Dr. Juan Manuel Frutos', NULL),
    ('Lucero del este', 'Jose Domingo Ocampos', 30000),
    ('ANDRES COURIER', 'Jose Domingo Ocampos', NULL),
    ('REINALDO COURIER', 'Jose Domingo Ocampos', NULL),
    ('WERAHA', 'Jose Domingo Ocampos', NULL),
    ('Lucero del este', 'La Pastora', NULL),
    ('ANDRES COURIER', 'La Pastora', NULL),
    ('REINALDO COURIER', 'La Pastora', NULL),
    ('WERAHA', 'La Pastora', NULL),
    ('Lucero del este', 'Mcal. Francisco Solano Lopez', NULL),
    ('ANDRES COURIER', 'Mcal. Francisco Solano Lopez', NULL),
    ('REINALDO COURIER', 'Mcal. Francisco Solano Lopez', NULL),
    ('WERAHA', 'Mcal. Francisco Solano Lopez', NULL),
    ('Lucero del este', 'Nueva Londres', NULL),
    ('ANDRES COURIER', 'Nueva Londres', NULL),
    ('REINALDO COURIER', 'Nueva Londres', NULL),
    ('WERAHA', 'Nueva Londres', NULL),
    ('Lucero del este', 'Nueva Toledo', NULL),
    ('ANDRES COURIER', 'Nueva Toledo', NULL),
    ('REINALDO COURIER', 'Nueva Toledo', NULL),
    ('WERAHA', 'Nueva Toledo', NULL),
    ('Lucero del este', 'R.I. 3 Corrales', NULL),
    ('ANDRES COURIER', 'R.I. 3 Corrales', NULL),
    ('REINALDO COURIER', 'R.I. 3 Corrales', NULL),
    ('WERAHA', 'R.I. 3 Corrales', NULL),
    ('Lucero del este', 'Raul Arsenio Oviedo', NULL),
    ('ANDRES COURIER', 'Raul Arsenio Oviedo', NULL),
    ('REINALDO COURIER', 'Raul Arsenio Oviedo', NULL),
    ('WERAHA', 'Raul Arsenio Oviedo', NULL),
    ('Lucero del este', 'Repatriacion', NULL),
    ('ANDRES COURIER', 'Repatriacion', NULL),
    ('REINALDO COURIER', 'Repatriacion', NULL),
    ('WERAHA', 'Repatriacion', NULL),
    ('Lucero del este', 'San Joaquin', NULL),
    ('ANDRES COURIER', 'San Joaquin', NULL),
    ('REINALDO COURIER', 'San Joaquin', NULL),
    ('WERAHA', 'San Joaquin', NULL),
    ('Lucero del este', 'San Jose de los Arroyos', NULL),
    ('ANDRES COURIER', 'San Jose de los Arroyos', NULL),
    ('REINALDO COURIER', 'San Jose de los Arroyos', NULL),
    ('WERAHA', 'San Jose de los Arroyos', NULL),
    ('Lucero del este', 'Santa Rosa del Mbutuy', NULL),
    ('ANDRES COURIER', 'Santa Rosa del Mbutuy', NULL),
    ('REINALDO COURIER', 'Santa Rosa del Mbutuy', NULL),
    ('WERAHA', 'Santa Rosa del Mbutuy', NULL),
    ('Lucero del este', 'Simon Bolivar', NULL),
    ('ANDRES COURIER', 'Simon Bolivar', NULL),
    ('REINALDO COURIER', 'Simon Bolivar', NULL),
    ('WERAHA', 'Simon Bolivar', NULL),
    ('Lucero del este', 'Tembiapora', NULL),
    ('ANDRES COURIER', 'Tembiapora', NULL),
    ('REINALDO COURIER', 'Tembiapora', NULL),
    ('WERAHA', 'Tembiapora', NULL),
    ('Lucero del este', 'Vaqueria', NULL),
    ('ANDRES COURIER', 'Vaqueria', NULL),
    ('REINALDO COURIER', 'Vaqueria', NULL),
    ('WERAHA', 'Vaqueria', NULL),
    ('Lucero del este', 'Yhu', NULL),
    ('ANDRES COURIER', 'Yhu', NULL),
    ('REINALDO COURIER', 'Yhu', NULL),
    ('WERAHA', 'Yhu', NULL),
    ('Lucero del este', '3 de mayo', NULL),
    ('ANDRES COURIER', '3 de mayo', NULL),
    ('REINALDO COURIER', '3 de mayo', NULL),
    ('WERAHA', '3 de mayo', NULL),
    ('Lucero del este', 'Abai', NULL),
    ('ANDRES COURIER', 'Abai', NULL),
    ('REINALDO COURIER', 'Abai', NULL),
    ('WERAHA', 'Abai', NULL),
    ('Lucero del este', 'Buena Vista', NULL),
    ('ANDRES COURIER', 'Buena Vista', NULL),
    ('REINALDO COURIER', 'Buena Vista', NULL),
    ('WERAHA', 'Buena Vista', NULL),
    ('Lucero del este', 'Caazapá', NULL),
    ('ANDRES COURIER', 'Caazapá', NULL),
    ('REINALDO COURIER', 'Caazapá', NULL),
    ('WERAHA', 'Caazapá', NULL),
    ('Lucero del este', 'Coronel Maciel', NULL),
    ('ANDRES COURIER', 'Coronel Maciel', NULL),
    ('REINALDO COURIER', 'Coronel Maciel', NULL),
    ('WERAHA', 'Coronel Maciel', NULL),
    ('Lucero del este', 'Doctor Moises S. Bertoni', NULL),
    ('ANDRES COURIER', 'Doctor Moises S. Bertoni', NULL),
    ('REINALDO COURIER', 'Doctor Moises S. Bertoni', NULL),
    ('WERAHA', 'Doctor Moises S. Bertoni', NULL),
    ('Lucero del este', 'Fulgencio Yegros', NULL),
    ('ANDRES COURIER', 'Fulgencio Yegros', NULL),
    ('REINALDO COURIER', 'Fulgencio Yegros', NULL),
    ('WERAHA', 'Fulgencio Yegros', NULL),
    ('Lucero del este', 'General Higinio Morínigo', NULL),
    ('ANDRES COURIER', 'General Higinio Morínigo', NULL),
    ('REINALDO COURIER', 'General Higinio Morínigo', NULL),
    ('WERAHA', 'General Higinio Morínigo', NULL),
    ('Lucero del este', 'San Juan Nepomuceno', NULL),
    ('ANDRES COURIER', 'San Juan Nepomuceno', NULL),
    ('REINALDO COURIER', 'San Juan Nepomuceno', NULL),
    ('WERAHA', 'San Juan Nepomuceno', NULL),
    ('Lucero del este', 'Tavaí', NULL),
    ('ANDRES COURIER', 'Tavaí', NULL),
    ('REINALDO COURIER', 'Tavaí', NULL),
    ('WERAHA', 'Tavaí', NULL),
    ('Lucero del este', 'Yuty', NULL),
    ('ANDRES COURIER', 'Yuty', NULL),
    ('REINALDO COURIER', 'Yuty', NULL),
    ('WERAHA', 'Yuty', NULL),
    ('Lucero del este', 'Corpus Christi', NULL),
    ('ANDRES COURIER', 'Corpus Christi', NULL),
    ('REINALDO COURIER', 'Corpus Christi', NULL),
    ('WERAHA', 'Corpus Christi', NULL),
    ('Lucero del este', 'Curuguaty', NULL),
    ('ANDRES COURIER', 'Curuguaty', NULL),
    ('REINALDO COURIER', 'Curuguaty', NULL),
    ('WERAHA', 'Curuguaty', NULL),
    ('Lucero del este', 'Gral. Francisco Caballero Álvarez', NULL),
    ('ANDRES COURIER', 'Gral. Francisco Caballero Álvarez', NULL),
    ('REINALDO COURIER', 'Gral. Francisco Caballero Álvarez', NULL),
    ('WERAHA', 'Gral. Francisco Caballero Álvarez', NULL),
    ('Lucero del este', 'Itanará', NULL),
    ('ANDRES COURIER', 'Itanará', NULL),
    ('REINALDO COURIER', 'Itanará', NULL),
    ('WERAHA', 'Itanará', NULL),
    ('Lucero del este', 'Katueté', 35000),
    ('ANDRES COURIER', 'Katueté', NULL),
    ('REINALDO COURIER', 'Katueté', NULL),
    ('WERAHA', 'Katueté', NULL),
    ('Lucero del este', 'La Paloma', 35000),
    ('ANDRES COURIER', 'La Paloma', NULL),
    ('REINALDO COURIER', 'La Paloma', NULL),
    ('WERAHA', 'La Paloma', NULL),
    ('Lucero del este', 'Maracaná', NULL),
    ('ANDRES COURIER', 'Maracaná', NULL),
    ('REINALDO COURIER', 'Maracaná', NULL),
    ('WERAHA', 'Maracaná', NULL),
    ('Lucero del este', 'Pto. Adela', NULL),
    ('ANDRES COURIER', 'Pto. Adela', NULL),
    ('REINALDO COURIER', 'Pto. Adela', NULL),
    ('WERAHA', 'Pto. Adela', NULL),
    ('Lucero del este', 'Laurel', NULL),
    ('ANDRES COURIER', 'Laurel', NULL),
    ('REINALDO COURIER', 'Laurel', NULL),
    ('WERAHA', 'Laurel', NULL),
    ('Lucero del este', 'Nueva Esperanza', 35000),
    ('ANDRES COURIER', 'Nueva Esperanza', NULL),
    ('REINALDO COURIER', 'Nueva Esperanza', NULL),
    ('WERAHA', 'Nueva Esperanza', NULL),
    ('Lucero del este', 'Salto del Guaira', NULL),
    ('ANDRES COURIER', 'Salto del Guaira', NULL),
    ('REINALDO COURIER', 'Salto del Guaira', NULL),
    ('WERAHA', 'Salto del Guaira', NULL),
    ('Lucero del este', 'Villa Ygatimí', NULL),
    ('ANDRES COURIER', 'Villa Ygatimí', NULL),
    ('REINALDO COURIER', 'Villa Ygatimí', NULL),
    ('WERAHA', 'Villa Ygatimí', NULL),
    ('Lucero del este', 'Yasy Cañy', NULL),
    ('ANDRES COURIER', 'Yasy Cañy', NULL),
    ('REINALDO COURIER', 'Yasy Cañy', NULL),
    ('WERAHA', 'Yasy Cañy', NULL),
    ('Lucero del este', 'Yby Pyta', NULL),
    ('ANDRES COURIER', 'Yby Pyta', NULL),
    ('REINALDO COURIER', 'Yby Pyta', NULL),
    ('WERAHA', 'Yby Pyta', NULL),
    ('Lucero del este', 'Ypejhú', NULL),
    ('ANDRES COURIER', 'Ypejhú', NULL),
    ('REINALDO COURIER', 'Ypejhú', NULL),
    ('WERAHA', 'Ypejhú', NULL),
    ('Lucero del este', 'Ybyrarobaná', NULL),
    ('ANDRES COURIER', 'Ybyrarobaná', NULL),
    ('REINALDO COURIER', 'Ybyrarobaná', NULL),
    ('WERAHA', 'Ybyrarobaná', NULL),
    ('Lucero del este', 'Areguá', 35000),
    ('ANDRES COURIER', 'Areguá', 20000),
    ('REINALDO COURIER', 'Areguá', 20000),
    ('WERAHA', 'Areguá', 24000),
    ('Lucero del este', 'Capiatá', 35000),
    ('ANDRES COURIER', 'Capiatá', 20000),
    ('REINALDO COURIER', 'Capiatá', 20000),
    ('WERAHA', 'Capiatá', 24000),
    ('Lucero del este', 'Fernando de la Mora', 30000),
    ('ANDRES COURIER', 'Fernando de la Mora', 18000),
    ('REINALDO COURIER', 'Fernando de la Mora', 18000),
    ('WERAHA', 'Fernando de la Mora', 24000),
    ('Lucero del este', 'Guarambaré', 35000),
    ('ANDRES COURIER', 'Guarambaré', 20000),
    ('REINALDO COURIER', 'Guarambaré', 20000),
    ('WERAHA', 'Guarambaré', 24000),
    ('Lucero del este', 'Itá', 35000),
    ('ANDRES COURIER', 'Itá', 30000),
    ('REINALDO COURIER', 'Itá', 30000),
    ('WERAHA', 'Itá', NULL),
    ('Lucero del este', 'Itauguá', 35000),
    ('ANDRES COURIER', 'Itauguá', 22000),
    ('REINALDO COURIER', 'Itauguá', 22000),
    ('WERAHA', 'Itauguá', 24000),
    ('Lucero del este', 'J. Augusto Saldivar', 30000),
    ('ANDRES COURIER', 'J. Augusto Saldivar', 22000),
    ('REINALDO COURIER', 'J. Augusto Saldivar', 22000),
    ('WERAHA', 'J. Augusto Saldivar', 24000),
    ('Lucero del este', 'Lambaré', 25000),
    ('ANDRES COURIER', 'Lambaré', 18000),
    ('REINALDO COURIER', 'Lambaré', 18000),
    ('WERAHA', 'Lambaré', 24000),
    ('Lucero del este', 'Limpio', 35000),
    ('ANDRES COURIER', 'Limpio', 20000),
    ('REINALDO COURIER', 'Limpio', 20000),
    ('WERAHA', 'Limpio', 24000),
    ('Lucero del este', 'Luque', 30000),
    ('ANDRES COURIER', 'Luque', 18000),
    ('REINALDO COURIER', 'Luque', 18000),
    ('WERAHA', 'Luque', 24000),
    ('Lucero del este', 'Mariano Roque Alonso', 30000),
    ('ANDRES COURIER', 'Mariano Roque Alonso', 18000),
    ('REINALDO COURIER', 'Mariano Roque Alonso', 18000),
    ('WERAHA', 'Mariano Roque Alonso', 24000),
    ('Lucero del este', 'Nueva Italia', 35000),
    ('ANDRES COURIER', 'Nueva Italia', NULL),
    ('REINALDO COURIER', 'Nueva Italia', NULL),
    ('WERAHA', 'Nueva Italia', NULL),
    ('Lucero del este', 'Ñemby', 35000),
    ('ANDRES COURIER', 'Ñemby', 20000),
    ('REINALDO COURIER', 'Ñemby', 20000),
    ('WERAHA', 'Ñemby', 24000),
    ('Lucero del este', 'San Antonio', 35000),
    ('ANDRES COURIER', 'San Antonio', 20000),
    ('REINALDO COURIER', 'San Antonio', 20000),
    ('WERAHA', 'San Antonio', 24000),
    ('Lucero del este', 'San Lorenzo', 25000),
    ('ANDRES COURIER', 'San Lorenzo', 18000),
    ('REINALDO COURIER', 'San Lorenzo', 18000),
    ('WERAHA', 'San Lorenzo', 24000),
    ('Lucero del este', 'Villa Elisa', 30000),
    ('ANDRES COURIER', 'Villa Elisa', 18000),
    ('REINALDO COURIER', 'Villa Elisa', 18000),
    ('WERAHA', 'Villa Elisa', 24000),
    ('Lucero del este', 'Villeta', 30000),
    ('ANDRES COURIER', 'Villeta', 30000),
    ('REINALDO COURIER', 'Villeta', 30000),
    ('WERAHA', 'Villeta', NULL),
    ('Lucero del este', 'Ypacaraí', 35000),
    ('ANDRES COURIER', 'Ypacaraí', NULL),
    ('REINALDO COURIER', 'Ypacaraí', NULL),
    ('WERAHA', 'Ypacaraí', NULL),
    ('Lucero del este', 'Ypané', 35000),
    ('ANDRES COURIER', 'Ypané', 20000),
    ('REINALDO COURIER', 'Ypané', 20000),
    ('WERAHA', 'Ypané', 24000),
    ('Lucero del este', 'Arroyito', NULL),
    ('ANDRES COURIER', 'Arroyito', NULL),
    ('REINALDO COURIER', 'Arroyito', NULL),
    ('WERAHA', 'Arroyito', NULL),
    ('Lucero del este', 'Azote''y', NULL),
    ('ANDRES COURIER', 'Azote''y', NULL),
    ('REINALDO COURIER', 'Azote''y', NULL),
    ('WERAHA', 'Azote''y', NULL),
    ('Lucero del este', 'Belén', NULL),
    ('ANDRES COURIER', 'Belén', NULL),
    ('REINALDO COURIER', 'Belén', NULL),
    ('WERAHA', 'Belén', NULL),
    ('Lucero del este', 'Concepción', 45000),
    ('ANDRES COURIER', 'Concepción', NULL),
    ('REINALDO COURIER', 'Concepción', NULL),
    ('WERAHA', 'Concepción', NULL),
    ('Lucero del este', 'Horqueta', 45000),
    ('ANDRES COURIER', 'Horqueta', NULL),
    ('REINALDO COURIER', 'Horqueta', NULL),
    ('WERAHA', 'Horqueta', NULL),
    ('Lucero del este', 'Loreto', NULL),
    ('ANDRES COURIER', 'Loreto', NULL),
    ('REINALDO COURIER', 'Loreto', NULL),
    ('WERAHA', 'Loreto', NULL),
    ('Lucero del este', 'Paso Barreto', NULL),
    ('ANDRES COURIER', 'Paso Barreto', NULL),
    ('REINALDO COURIER', 'Paso Barreto', NULL),
    ('WERAHA', 'Paso Barreto', NULL),
    ('Lucero del este', 'Paso Horqueta', NULL),
    ('ANDRES COURIER', 'Paso Horqueta', NULL),
    ('REINALDO COURIER', 'Paso Horqueta', NULL),
    ('WERAHA', 'Paso Horqueta', NULL),
    ('Lucero del este', 'San Alfredo', NULL),
    ('ANDRES COURIER', 'San Alfredo', NULL),
    ('REINALDO COURIER', 'San Alfredo', NULL),
    ('WERAHA', 'San Alfredo', NULL),
    ('Lucero del este', 'San Lázaro', NULL),
    ('ANDRES COURIER', 'San Lázaro', NULL),
    ('REINALDO COURIER', 'San Lázaro', NULL),
    ('WERAHA', 'San Lázaro', NULL),
    ('Lucero del este', 'San Carlos del Apa', NULL),
    ('ANDRES COURIER', 'San Carlos del Apa', NULL),
    ('REINALDO COURIER', 'San Carlos del Apa', NULL),
    ('WERAHA', 'San Carlos del Apa', NULL),
    ('Lucero del este', 'Sargento Jose Felix Lopez', NULL),
    ('ANDRES COURIER', 'Sargento Jose Felix Lopez', NULL),
    ('REINALDO COURIER', 'Sargento Jose Felix Lopez', NULL),
    ('WERAHA', 'Sargento Jose Felix Lopez', NULL),
    ('Lucero del este', 'Yby Yaú', NULL),
    ('ANDRES COURIER', 'Yby Yaú', NULL),
    ('REINALDO COURIER', 'Yby Yaú', NULL),
    ('WERAHA', 'Yby Yaú', NULL),
    ('Lucero del este', 'Altos', 35000),
    ('ANDRES COURIER', 'Altos', NULL),
    ('REINALDO COURIER', 'Altos', NULL),
    ('WERAHA', 'Altos', NULL),
    ('Lucero del este', 'Arroyos y Esteros', NULL),
    ('ANDRES COURIER', 'Arroyos y Esteros', NULL),
    ('REINALDO COURIER', 'Arroyos y Esteros', NULL),
    ('WERAHA', 'Arroyos y Esteros', NULL),
    ('Lucero del este', 'Atyrá', 35000),
    ('ANDRES COURIER', 'Atyrá', NULL),
    ('REINALDO COURIER', 'Atyrá', NULL),
    ('WERAHA', 'Atyrá', NULL),
    ('Lucero del este', 'Caacupé', 35000),
    ('ANDRES COURIER', 'Caacupé', NULL),
    ('REINALDO COURIER', 'Caacupé', NULL),
    ('WERAHA', 'Caacupé', NULL),
    ('Lucero del este', 'Caraguatay', NULL),
    ('ANDRES COURIER', 'Caraguatay', NULL),
    ('REINALDO COURIER', 'Caraguatay', NULL),
    ('WERAHA', 'Caraguatay', NULL),
    ('Lucero del este', 'Emboscada', NULL),
    ('ANDRES COURIER', 'Emboscada', NULL),
    ('REINALDO COURIER', 'Emboscada', NULL),
    ('WERAHA', 'Emboscada', NULL),
    ('Lucero del este', 'Eusebio Ayala', 35000),
    ('ANDRES COURIER', 'Eusebio Ayala', NULL),
    ('REINALDO COURIER', 'Eusebio Ayala', NULL),
    ('WERAHA', 'Eusebio Ayala', NULL),
    ('Lucero del este', 'Isla Pucú', NULL),
    ('ANDRES COURIER', 'Isla Pucú', NULL),
    ('REINALDO COURIER', 'Isla Pucú', NULL),
    ('WERAHA', 'Isla Pucú', NULL),
    ('Lucero del este', 'Itacurubí de la Cordillera', NULL),
    ('ANDRES COURIER', 'Itacurubí de la Cordillera', NULL),
    ('REINALDO COURIER', 'Itacurubí de la Cordillera', NULL),
    ('WERAHA', 'Itacurubí de la Cordillera', NULL),
    ('Lucero del este', 'Juan de Mena', NULL),
    ('ANDRES COURIER', 'Juan de Mena', NULL),
    ('REINALDO COURIER', 'Juan de Mena', NULL),
    ('WERAHA', 'Juan de Mena', NULL),
    ('Lucero del este', 'Loma Grande', NULL),
    ('ANDRES COURIER', 'Loma Grande', NULL),
    ('REINALDO COURIER', 'Loma Grande', NULL),
    ('WERAHA', 'Loma Grande', NULL),
    ('Lucero del este', 'Mbocayaty del Yhaguy', NULL),
    ('ANDRES COURIER', 'Mbocayaty del Yhaguy', NULL),
    ('REINALDO COURIER', 'Mbocayaty del Yhaguy', NULL),
    ('WERAHA', 'Mbocayaty del Yhaguy', NULL),
    ('Lucero del este', 'Nueva Colombia', NULL),
    ('ANDRES COURIER', 'Nueva Colombia', NULL),
    ('REINALDO COURIER', 'Nueva Colombia', NULL),
    ('WERAHA', 'Nueva Colombia', NULL),
    ('Lucero del este', 'Piribebuy', 35000),
    ('ANDRES COURIER', 'Piribebuy', NULL),
    ('REINALDO COURIER', 'Piribebuy', NULL),
    ('WERAHA', 'Piribebuy', NULL),
    ('Lucero del este', 'Primero de Marzo', NULL),
    ('ANDRES COURIER', 'Primero de Marzo', NULL),
    ('REINALDO COURIER', 'Primero de Marzo', NULL),
    ('WERAHA', 'Primero de Marzo', NULL),
    ('Lucero del este', 'San Bernardino', 35000),
    ('ANDRES COURIER', 'San Bernardino', NULL),
    ('REINALDO COURIER', 'San Bernardino', NULL),
    ('WERAHA', 'San Bernardino', NULL),
    ('Lucero del este', 'San José Obrero', 35000),
    ('ANDRES COURIER', 'San José Obrero', NULL),
    ('REINALDO COURIER', 'San José Obrero', NULL),
    ('WERAHA', 'San José Obrero', NULL),
    ('Lucero del este', 'Santa Elena', NULL),
    ('ANDRES COURIER', 'Santa Elena', NULL),
    ('REINALDO COURIER', 'Santa Elena', NULL),
    ('WERAHA', 'Santa Elena', NULL),
    ('Lucero del este', 'Tobatí', 35000),
    ('ANDRES COURIER', 'Tobatí', NULL),
    ('REINALDO COURIER', 'Tobatí', NULL),
    ('WERAHA', 'Tobatí', NULL),
    ('Lucero del este', 'Valenzuela', NULL),
    ('ANDRES COURIER', 'Valenzuela', NULL),
    ('REINALDO COURIER', 'Valenzuela', NULL),
    ('WERAHA', 'Valenzuela', NULL),
    ('Lucero del este', 'Coronel Martinez', NULL),
    ('ANDRES COURIER', 'Coronel Martinez', NULL),
    ('REINALDO COURIER', 'Coronel Martinez', NULL),
    ('WERAHA', 'Coronel Martinez', NULL),
    ('Lucero del este', 'Borja', NULL),
    ('ANDRES COURIER', 'Borja', NULL),
    ('REINALDO COURIER', 'Borja', NULL),
    ('WERAHA', 'Borja', NULL),
    ('Lucero del este', 'Doctor Botrell', NULL),
    ('ANDRES COURIER', 'Doctor Botrell', NULL),
    ('REINALDO COURIER', 'Doctor Botrell', NULL),
    ('WERAHA', 'Doctor Botrell', NULL),
    ('Lucero del este', 'Eugenio A. Garay', NULL),
    ('ANDRES COURIER', 'Eugenio A. Garay', NULL),
    ('REINALDO COURIER', 'Eugenio A. Garay', NULL),
    ('WERAHA', 'Eugenio A. Garay', NULL),
    ('Lucero del este', 'Félix Pérez Cardozo', NULL),
    ('ANDRES COURIER', 'Félix Pérez Cardozo', NULL),
    ('REINALDO COURIER', 'Félix Pérez Cardozo', NULL),
    ('WERAHA', 'Félix Pérez Cardozo', NULL),
    ('Lucero del este', 'Independencia', NULL),
    ('ANDRES COURIER', 'Independencia', NULL),
    ('REINALDO COURIER', 'Independencia', NULL),
    ('WERAHA', 'Independencia', NULL),
    ('Lucero del este', 'Itapé', NULL),
    ('ANDRES COURIER', 'Itapé', NULL),
    ('REINALDO COURIER', 'Itapé', NULL),
    ('WERAHA', 'Itapé', NULL),
    ('Lucero del este', 'Iturbe', NULL),
    ('ANDRES COURIER', 'Iturbe', NULL),
    ('REINALDO COURIER', 'Iturbe', NULL),
    ('WERAHA', 'Iturbe', NULL),
    ('Lucero del este', 'José Fassardi', NULL),
    ('ANDRES COURIER', 'José Fassardi', NULL),
    ('REINALDO COURIER', 'José Fassardi', NULL),
    ('WERAHA', 'José Fassardi', NULL),
    ('Lucero del este', 'Jose Mauricio Troche', NULL),
    ('ANDRES COURIER', 'Jose Mauricio Troche', NULL),
    ('REINALDO COURIER', 'Jose Mauricio Troche', NULL),
    ('WERAHA', 'Jose Mauricio Troche', NULL),
    ('Lucero del este', 'Mbocayaty del Guairá', NULL),
    ('ANDRES COURIER', 'Mbocayaty del Guairá', NULL),
    ('REINALDO COURIER', 'Mbocayaty del Guairá', NULL),
    ('WERAHA', 'Mbocayaty del Guairá', NULL),
    ('Lucero del este', 'Natalicio Talavera', NULL),
    ('ANDRES COURIER', 'Natalicio Talavera', NULL),
    ('REINALDO COURIER', 'Natalicio Talavera', NULL),
    ('WERAHA', 'Natalicio Talavera', NULL),
    ('Lucero del este', 'Ñumi', NULL),
    ('ANDRES COURIER', 'Ñumi', NULL),
    ('REINALDO COURIER', 'Ñumi', NULL),
    ('WERAHA', 'Ñumi', NULL),
    ('Lucero del este', 'Paso Yobai', NULL),
    ('ANDRES COURIER', 'Paso Yobai', NULL),
    ('REINALDO COURIER', 'Paso Yobai', NULL),
    ('WERAHA', 'Paso Yobai', NULL),
    ('Lucero del este', 'San Salvador', NULL),
    ('ANDRES COURIER', 'San Salvador', NULL),
    ('REINALDO COURIER', 'San Salvador', NULL),
    ('WERAHA', 'San Salvador', NULL),
    ('Lucero del este', 'Tebicuary', NULL),
    ('ANDRES COURIER', 'Tebicuary', NULL),
    ('REINALDO COURIER', 'Tebicuary', NULL),
    ('WERAHA', 'Tebicuary', NULL),
    ('Lucero del este', 'Villarrica', 40000),
    ('ANDRES COURIER', 'Villarrica', NULL),
    ('REINALDO COURIER', 'Villarrica', NULL),
    ('WERAHA', 'Villarrica', NULL),
    ('Lucero del este', 'Yataity', NULL),
    ('ANDRES COURIER', 'Yataity', NULL),
    ('REINALDO COURIER', 'Yataity', NULL),
    ('WERAHA', 'Yataity', NULL),
    ('Lucero del este', 'Alto Vera', NULL),
    ('ANDRES COURIER', 'Alto Vera', NULL),
    ('REINALDO COURIER', 'Alto Vera', NULL),
    ('WERAHA', 'Alto Vera', NULL),
    ('Lucero del este', 'Bella Vista', NULL),
    ('ANDRES COURIER', 'Bella Vista', NULL),
    ('REINALDO COURIER', 'Bella Vista', NULL),
    ('WERAHA', 'Bella Vista', NULL),
    ('Lucero del este', 'Cambyreta', NULL),
    ('ANDRES COURIER', 'Cambyreta', NULL),
    ('REINALDO COURIER', 'Cambyreta', NULL),
    ('WERAHA', 'Cambyreta', NULL),
    ('Lucero del este', 'Capitan Meza', NULL),
    ('ANDRES COURIER', 'Capitan Meza', NULL),
    ('REINALDO COURIER', 'Capitan Meza', NULL),
    ('WERAHA', 'Capitan Meza', NULL),
    ('Lucero del este', 'Capitan Miranda', NULL),
    ('ANDRES COURIER', 'Capitan Miranda', NULL),
    ('REINALDO COURIER', 'Capitan Miranda', NULL),
    ('WERAHA', 'Capitan Miranda', NULL),
    ('Lucero del este', 'Carlos Antonio López', NULL),
    ('ANDRES COURIER', 'Carlos Antonio López', NULL),
    ('REINALDO COURIER', 'Carlos Antonio López', NULL),
    ('WERAHA', 'Carlos Antonio López', NULL),
    ('Lucero del este', 'Carmen del Parana', NULL),
    ('ANDRES COURIER', 'Carmen del Parana', NULL),
    ('REINALDO COURIER', 'Carmen del Parana', NULL),
    ('WERAHA', 'Carmen del Parana', NULL),
    ('Lucero del este', 'Coronel Bogado', NULL),
    ('ANDRES COURIER', 'Coronel Bogado', NULL),
    ('REINALDO COURIER', 'Coronel Bogado', NULL),
    ('WERAHA', 'Coronel Bogado', NULL),
    ('Lucero del este', 'Edelira', NULL),
    ('ANDRES COURIER', 'Edelira', NULL),
    ('REINALDO COURIER', 'Edelira', NULL),
    ('WERAHA', 'Edelira', NULL),
    ('Lucero del este', 'Encarnación', 35000),
    ('ANDRES COURIER', 'Encarnación', NULL),
    ('REINALDO COURIER', 'Encarnación', NULL),
    ('WERAHA', 'Encarnación', NULL),
    ('Lucero del este', 'Fram', NULL),
    ('ANDRES COURIER', 'Fram', NULL),
    ('REINALDO COURIER', 'Fram', NULL),
    ('WERAHA', 'Fram', NULL),
    ('Lucero del este', 'General Jose Maria Delgado', NULL),
    ('ANDRES COURIER', 'General Jose Maria Delgado', NULL),
    ('REINALDO COURIER', 'General Jose Maria Delgado', NULL),
    ('WERAHA', 'General Jose Maria Delgado', NULL),
    ('Lucero del este', 'Gral. Artigas', NULL),
    ('ANDRES COURIER', 'Gral. Artigas', NULL),
    ('REINALDO COURIER', 'Gral. Artigas', NULL),
    ('WERAHA', 'Gral. Artigas', NULL),
    ('Lucero del este', 'Hohenau', NULL),
    ('ANDRES COURIER', 'Hohenau', NULL),
    ('REINALDO COURIER', 'Hohenau', NULL),
    ('WERAHA', 'Hohenau', NULL),
    ('Lucero del este', 'Itapua Poty', NULL),
    ('ANDRES COURIER', 'Itapua Poty', NULL),
    ('REINALDO COURIER', 'Itapua Poty', NULL),
    ('WERAHA', 'Itapua Poty', NULL),
    ('Lucero del este', 'Jesús de Tavarangué', NULL),
    ('ANDRES COURIER', 'Jesús de Tavarangué', NULL),
    ('REINALDO COURIER', 'Jesús de Tavarangué', NULL),
    ('WERAHA', 'Jesús de Tavarangué', NULL),
    ('Lucero del este', 'Jose Leandro Oviedo', NULL),
    ('ANDRES COURIER', 'Jose Leandro Oviedo', NULL),
    ('REINALDO COURIER', 'Jose Leandro Oviedo', NULL),
    ('WERAHA', 'Jose Leandro Oviedo', NULL),
    ('Lucero del este', 'La Paz', NULL),
    ('ANDRES COURIER', 'La Paz', NULL),
    ('REINALDO COURIER', 'La Paz', NULL),
    ('WERAHA', 'La Paz', NULL),
    ('Lucero del este', 'Mayor Otaño', NULL),
    ('ANDRES COURIER', 'Mayor Otaño', NULL),
    ('REINALDO COURIER', 'Mayor Otaño', NULL),
    ('WERAHA', 'Mayor Otaño', NULL),
    ('Lucero del este', 'Natalio', NULL),
    ('ANDRES COURIER', 'Natalio', NULL),
    ('REINALDO COURIER', 'Natalio', NULL),
    ('WERAHA', 'Natalio', NULL),
    ('Lucero del este', 'Nueva Alborada', NULL),
    ('ANDRES COURIER', 'Nueva Alborada', NULL),
    ('REINALDO COURIER', 'Nueva Alborada', NULL),
    ('WERAHA', 'Nueva Alborada', NULL),
    ('Lucero del este', 'Obligado', NULL),
    ('ANDRES COURIER', 'Obligado', NULL),
    ('REINALDO COURIER', 'Obligado', NULL),
    ('WERAHA', 'Obligado', NULL),
    ('Lucero del este', 'Pirapo', NULL),
    ('ANDRES COURIER', 'Pirapo', NULL),
    ('REINALDO COURIER', 'Pirapo', NULL),
    ('WERAHA', 'Pirapo', NULL),
    ('Lucero del este', 'San Cosme y Damián', NULL),
    ('ANDRES COURIER', 'San Cosme y Damián', NULL),
    ('REINALDO COURIER', 'San Cosme y Damián', NULL),
    ('WERAHA', 'San Cosme y Damián', NULL),
    ('Lucero del este', 'San Juan del Paraná', NULL),
    ('ANDRES COURIER', 'San Juan del Paraná', NULL),
    ('REINALDO COURIER', 'San Juan del Paraná', NULL),
    ('WERAHA', 'San Juan del Paraná', NULL),
    ('Lucero del este', 'San Pedro del Paraná', NULL),
    ('ANDRES COURIER', 'San Pedro del Paraná', NULL),
    ('REINALDO COURIER', 'San Pedro del Paraná', NULL),
    ('WERAHA', 'San Pedro del Paraná', NULL),
    ('Lucero del este', 'San Rafael del Parana', NULL),
    ('ANDRES COURIER', 'San Rafael del Parana', NULL),
    ('REINALDO COURIER', 'San Rafael del Parana', NULL),
    ('WERAHA', 'San Rafael del Parana', NULL),
    ('Lucero del este', 'Tomas R. Pereira', NULL),
    ('ANDRES COURIER', 'Tomas R. Pereira', NULL),
    ('REINALDO COURIER', 'Tomas R. Pereira', NULL),
    ('WERAHA', 'Tomas R. Pereira', NULL),
    ('Lucero del este', 'Trinidad', NULL),
    ('ANDRES COURIER', 'Trinidad', NULL),
    ('REINALDO COURIER', 'Trinidad', NULL),
    ('WERAHA', 'Trinidad', NULL),
    ('Lucero del este', 'Yatytay', NULL),
    ('ANDRES COURIER', 'Yatytay', NULL),
    ('REINALDO COURIER', 'Yatytay', NULL),
    ('WERAHA', 'Yatytay', NULL),
    ('Lucero del este', 'Ayolas', NULL),
    ('ANDRES COURIER', 'Ayolas', NULL),
    ('REINALDO COURIER', 'Ayolas', NULL),
    ('WERAHA', 'Ayolas', NULL),
    ('Lucero del este', 'San Ignacio Guazú', NULL),
    ('ANDRES COURIER', 'San Ignacio Guazú', NULL),
    ('REINALDO COURIER', 'San Ignacio Guazú', NULL),
    ('WERAHA', 'San Ignacio Guazú', NULL),
    ('Lucero del este', 'San Juan Bautista', NULL),
    ('ANDRES COURIER', 'San Juan Bautista', NULL),
    ('REINALDO COURIER', 'San Juan Bautista', NULL),
    ('WERAHA', 'San Juan Bautista', NULL),
    ('Lucero del este', 'San Miguel', NULL),
    ('ANDRES COURIER', 'San Miguel', NULL),
    ('REINALDO COURIER', 'San Miguel', NULL),
    ('WERAHA', 'San Miguel', NULL),
    ('Lucero del este', 'San Patricio', NULL),
    ('ANDRES COURIER', 'San Patricio', NULL),
    ('REINALDO COURIER', 'San Patricio', NULL),
    ('WERAHA', 'San Patricio', NULL),
    ('Lucero del este', 'Santa María de Fé', NULL),
    ('ANDRES COURIER', 'Santa María de Fé', NULL),
    ('REINALDO COURIER', 'Santa María de Fé', NULL),
    ('WERAHA', 'Santa María de Fé', NULL),
    ('Lucero del este', 'Santa Rosa Misiones', NULL),
    ('ANDRES COURIER', 'Santa Rosa Misiones', NULL),
    ('REINALDO COURIER', 'Santa Rosa Misiones', NULL),
    ('WERAHA', 'Santa Rosa Misiones', NULL),
    ('Lucero del este', 'Santiago', NULL),
    ('ANDRES COURIER', 'Santiago', NULL),
    ('REINALDO COURIER', 'Santiago', NULL),
    ('WERAHA', 'Santiago', NULL),
    ('Lucero del este', 'Villa Florida', NULL),
    ('ANDRES COURIER', 'Villa Florida', NULL),
    ('REINALDO COURIER', 'Villa Florida', NULL),
    ('WERAHA', 'Villa Florida', NULL),
    ('Lucero del este', 'Yabebyry', NULL),
    ('ANDRES COURIER', 'Yabebyry', NULL),
    ('REINALDO COURIER', 'Yabebyry', NULL),
    ('WERAHA', 'Yabebyry', NULL),
    ('Lucero del este', 'Alberdi', NULL),
    ('ANDRES COURIER', 'Alberdi', NULL),
    ('REINALDO COURIER', 'Alberdi', NULL),
    ('WERAHA', 'Alberdi', NULL),
    ('Lucero del este', 'Cerrito', NULL),
    ('ANDRES COURIER', 'Cerrito', NULL),
    ('REINALDO COURIER', 'Cerrito', NULL),
    ('WERAHA', 'Cerrito', NULL),
    ('Lucero del este', 'Desmochados', NULL),
    ('ANDRES COURIER', 'Desmochados', NULL),
    ('REINALDO COURIER', 'Desmochados', NULL),
    ('WERAHA', 'Desmochados', NULL),
    ('Lucero del este', 'Gral. José E. Díaz', NULL),
    ('ANDRES COURIER', 'Gral. José E. Díaz', NULL),
    ('REINALDO COURIER', 'Gral. José E. Díaz', NULL),
    ('WERAHA', 'Gral. José E. Díaz', NULL),
    ('Lucero del este', 'Guazucuá', NULL),
    ('ANDRES COURIER', 'Guazucuá', NULL),
    ('REINALDO COURIER', 'Guazucuá', NULL),
    ('WERAHA', 'Guazucuá', NULL),
    ('Lucero del este', 'Humaitá', NULL),
    ('ANDRES COURIER', 'Humaitá', NULL),
    ('REINALDO COURIER', 'Humaitá', NULL),
    ('WERAHA', 'Humaitá', NULL),
    ('Lucero del este', 'Isla Umbú', NULL),
    ('ANDRES COURIER', 'Isla Umbú', NULL),
    ('REINALDO COURIER', 'Isla Umbú', NULL),
    ('WERAHA', 'Isla Umbú', NULL),
    ('Lucero del este', 'Laureles', NULL),
    ('ANDRES COURIER', 'Laureles', NULL),
    ('REINALDO COURIER', 'Laureles', NULL),
    ('WERAHA', 'Laureles', NULL),
    ('Lucero del este', 'Mayor José D. Martínez', NULL),
    ('ANDRES COURIER', 'Mayor José D. Martínez', NULL),
    ('REINALDO COURIER', 'Mayor José D. Martínez', NULL),
    ('WERAHA', 'Mayor José D. Martínez', NULL),
    ('Lucero del este', 'Paso de Patria', NULL),
    ('ANDRES COURIER', 'Paso de Patria', NULL),
    ('REINALDO COURIER', 'Paso de Patria', NULL),
    ('WERAHA', 'Paso de Patria', NULL),
    ('Lucero del este', 'Pilar', NULL),
    ('ANDRES COURIER', 'Pilar', NULL),
    ('REINALDO COURIER', 'Pilar', NULL),
    ('WERAHA', 'Pilar', NULL),
    ('Lucero del este', 'San Juan Bautista del Ñeembucú', NULL),
    ('ANDRES COURIER', 'San Juan Bautista del Ñeembucú', NULL),
    ('REINALDO COURIER', 'San Juan Bautista del Ñeembucú', NULL),
    ('WERAHA', 'San Juan Bautista del Ñeembucú', NULL),
    ('Lucero del este', 'Tacuaras', NULL),
    ('ANDRES COURIER', 'Tacuaras', NULL),
    ('REINALDO COURIER', 'Tacuaras', NULL),
    ('WERAHA', 'Tacuaras', NULL),
    ('Lucero del este', 'Villa Franca', NULL),
    ('ANDRES COURIER', 'Villa Franca', NULL),
    ('REINALDO COURIER', 'Villa Franca', NULL),
    ('WERAHA', 'Villa Franca', NULL),
    ('Lucero del este', 'Villa Oliva', NULL),
    ('ANDRES COURIER', 'Villa Oliva', NULL),
    ('REINALDO COURIER', 'Villa Oliva', NULL),
    ('WERAHA', 'Villa Oliva', NULL),
    ('Lucero del este', 'Villalbin', NULL),
    ('ANDRES COURIER', 'Villalbin', NULL),
    ('REINALDO COURIER', 'Villalbin', NULL),
    ('WERAHA', 'Villalbin', NULL),
    ('Lucero del este', 'Acahay', NULL),
    ('ANDRES COURIER', 'Acahay', NULL),
    ('REINALDO COURIER', 'Acahay', NULL),
    ('WERAHA', 'Acahay', NULL),
    ('Lucero del este', 'Caapucú', NULL),
    ('ANDRES COURIER', 'Caapucú', NULL),
    ('REINALDO COURIER', 'Caapucú', NULL),
    ('WERAHA', 'Caapucú', NULL),
    ('Lucero del este', 'Carapeguá', NULL),
    ('ANDRES COURIER', 'Carapeguá', NULL),
    ('REINALDO COURIER', 'Carapeguá', NULL),
    ('WERAHA', 'Carapeguá', NULL),
    ('Lucero del este', 'Escobar', NULL),
    ('ANDRES COURIER', 'Escobar', NULL),
    ('REINALDO COURIER', 'Escobar', NULL),
    ('WERAHA', 'Escobar', NULL),
    ('Lucero del este', 'Gral. Bernardino Caballero', NULL),
    ('ANDRES COURIER', 'Gral. Bernardino Caballero', NULL),
    ('REINALDO COURIER', 'Gral. Bernardino Caballero', NULL),
    ('WERAHA', 'Gral. Bernardino Caballero', NULL),
    ('Lucero del este', 'La Colmena', NULL),
    ('ANDRES COURIER', 'La Colmena', NULL),
    ('REINALDO COURIER', 'La Colmena', NULL),
    ('WERAHA', 'La Colmena', NULL),
    ('Lucero del este', 'María Antonia', NULL),
    ('ANDRES COURIER', 'María Antonia', NULL),
    ('REINALDO COURIER', 'María Antonia', NULL),
    ('WERAHA', 'María Antonia', NULL),
    ('Lucero del este', 'Mbuyapey', NULL),
    ('ANDRES COURIER', 'Mbuyapey', NULL),
    ('REINALDO COURIER', 'Mbuyapey', NULL),
    ('WERAHA', 'Mbuyapey', NULL),
    ('Lucero del este', 'Paraguarí', 35000),
    ('ANDRES COURIER', 'Paraguarí', NULL),
    ('REINALDO COURIER', 'Paraguarí', NULL),
    ('WERAHA', 'Paraguarí', NULL),
    ('Lucero del este', 'Pirayú', NULL),
    ('ANDRES COURIER', 'Pirayú', NULL),
    ('REINALDO COURIER', 'Pirayú', NULL),
    ('WERAHA', 'Pirayú', NULL),
    ('Lucero del este', 'Quiindy', NULL),
    ('ANDRES COURIER', 'Quiindy', NULL),
    ('REINALDO COURIER', 'Quiindy', NULL),
    ('WERAHA', 'Quiindy', NULL),
    ('Lucero del este', 'Quyquyhó', NULL),
    ('ANDRES COURIER', 'Quyquyhó', NULL),
    ('REINALDO COURIER', 'Quyquyhó', NULL),
    ('WERAHA', 'Quyquyhó', NULL),
    ('Lucero del este', 'San Roque González de Santa Cruz', NULL),
    ('ANDRES COURIER', 'San Roque González de Santa Cruz', NULL),
    ('REINALDO COURIER', 'San Roque González de Santa Cruz', NULL),
    ('WERAHA', 'San Roque González de Santa Cruz', NULL),
    ('Lucero del este', 'Sapucai', NULL),
    ('ANDRES COURIER', 'Sapucai', NULL),
    ('REINALDO COURIER', 'Sapucai', NULL),
    ('WERAHA', 'Sapucai', NULL),
    ('Lucero del este', 'Tebicuarymí', NULL),
    ('ANDRES COURIER', 'Tebicuarymí', NULL),
    ('REINALDO COURIER', 'Tebicuarymí', NULL),
    ('WERAHA', 'Tebicuarymí', NULL),
    ('Lucero del este', 'Yaguarón', 35000),
    ('ANDRES COURIER', 'Yaguarón', NULL),
    ('REINALDO COURIER', 'Yaguarón', NULL),
    ('WERAHA', 'Yaguarón', NULL),
    ('Lucero del este', 'Ybycuí', NULL),
    ('ANDRES COURIER', 'Ybycuí', NULL),
    ('REINALDO COURIER', 'Ybycuí', NULL),
    ('WERAHA', 'Ybycuí', NULL),
    ('Lucero del este', 'Ybytymí', NULL),
    ('ANDRES COURIER', 'Ybytymí', NULL),
    ('REINALDO COURIER', 'Ybytymí', NULL),
    ('WERAHA', 'Ybytymí', NULL),
    ('Lucero del este', 'Benjamin Aceval', NULL),
    ('ANDRES COURIER', 'Benjamin Aceval', NULL),
    ('REINALDO COURIER', 'Benjamin Aceval', NULL),
    ('WERAHA', 'Benjamin Aceval', NULL),
    ('Lucero del este', 'Campo Aceval', NULL),
    ('ANDRES COURIER', 'Campo Aceval', NULL),
    ('REINALDO COURIER', 'Campo Aceval', NULL),
    ('WERAHA', 'Campo Aceval', NULL),
    ('Lucero del este', 'Gral. Jose Maria Bruguez', NULL),
    ('ANDRES COURIER', 'Gral. Jose Maria Bruguez', NULL),
    ('REINALDO COURIER', 'Gral. Jose Maria Bruguez', NULL),
    ('WERAHA', 'Gral. Jose Maria Bruguez', NULL),
    ('Lucero del este', 'José Falcón', NULL),
    ('ANDRES COURIER', 'José Falcón', NULL),
    ('REINALDO COURIER', 'José Falcón', NULL),
    ('WERAHA', 'José Falcón', NULL),
    ('Lucero del este', 'Nueva Asunción', NULL),
    ('ANDRES COURIER', 'Nueva Asunción', NULL),
    ('REINALDO COURIER', 'Nueva Asunción', NULL),
    ('WERAHA', 'Nueva Asunción', NULL),
    ('Lucero del este', 'Nanawa', NULL),
    ('ANDRES COURIER', 'Nanawa', NULL),
    ('REINALDO COURIER', 'Nanawa', NULL),
    ('WERAHA', 'Nanawa', NULL),
    ('Lucero del este', 'Puerto Pinasco', NULL),
    ('ANDRES COURIER', 'Puerto Pinasco', NULL),
    ('REINALDO COURIER', 'Puerto Pinasco', NULL),
    ('WERAHA', 'Puerto Pinasco', NULL),
    ('Lucero del este', 'Tte. 1ro Manuel Irala Fernandez', NULL),
    ('ANDRES COURIER', 'Tte. 1ro Manuel Irala Fernandez', NULL),
    ('REINALDO COURIER', 'Tte. 1ro Manuel Irala Fernandez', NULL),
    ('WERAHA', 'Tte. 1ro Manuel Irala Fernandez', NULL),
    ('Lucero del este', 'Tte. Esteban Martinez', NULL),
    ('ANDRES COURIER', 'Tte. Esteban Martinez', NULL),
    ('REINALDO COURIER', 'Tte. Esteban Martinez', NULL),
    ('WERAHA', 'Tte. Esteban Martinez', NULL),
    ('Lucero del este', 'Villa Hayes', NULL),
    ('ANDRES COURIER', 'Villa Hayes', NULL),
    ('REINALDO COURIER', 'Villa Hayes', NULL),
    ('WERAHA', 'Villa Hayes', NULL),
    ('Lucero del este', '25 de diciembre', NULL),
    ('ANDRES COURIER', '25 de diciembre', NULL),
    ('REINALDO COURIER', '25 de diciembre', NULL),
    ('WERAHA', '25 de diciembre', NULL),
    ('Lucero del este', 'Antequera', NULL),
    ('ANDRES COURIER', 'Antequera', NULL),
    ('REINALDO COURIER', 'Antequera', NULL),
    ('WERAHA', 'Antequera', NULL),
    ('Lucero del este', 'Capiibary', NULL),
    ('ANDRES COURIER', 'Capiibary', NULL),
    ('REINALDO COURIER', 'Capiibary', NULL),
    ('WERAHA', 'Capiibary', NULL),
    ('Lucero del este', 'Choré', NULL),
    ('ANDRES COURIER', 'Choré', NULL),
    ('REINALDO COURIER', 'Choré', NULL),
    ('WERAHA', 'Choré', NULL),
    ('Lucero del este', 'Gral. Elizardo Aquino', NULL),
    ('ANDRES COURIER', 'Gral. Elizardo Aquino', NULL),
    ('REINALDO COURIER', 'Gral. Elizardo Aquino', NULL),
    ('WERAHA', 'Gral. Elizardo Aquino', NULL),
    ('Lucero del este', 'Gral. Resquín', NULL),
    ('ANDRES COURIER', 'Gral. Resquín', NULL),
    ('REINALDO COURIER', 'Gral. Resquín', NULL),
    ('WERAHA', 'Gral. Resquín', NULL),
    ('Lucero del este', 'Guayaibí', NULL),
    ('ANDRES COURIER', 'Guayaibí', NULL),
    ('REINALDO COURIER', 'Guayaibí', NULL),
    ('WERAHA', 'Guayaibí', NULL),
    ('Lucero del este', 'Itacurubí del Rosario', NULL),
    ('ANDRES COURIER', 'Itacurubí del Rosario', NULL),
    ('REINALDO COURIER', 'Itacurubí del Rosario', NULL),
    ('WERAHA', 'Itacurubí del Rosario', NULL),
    ('Lucero del este', 'Liberación', NULL),
    ('ANDRES COURIER', 'Liberación', NULL),
    ('REINALDO COURIER', 'Liberación', NULL),
    ('WERAHA', 'Liberación', NULL),
    ('Lucero del este', 'Lima', NULL),
    ('ANDRES COURIER', 'Lima', NULL),
    ('REINALDO COURIER', 'Lima', NULL),
    ('WERAHA', 'Lima', NULL),
    ('Lucero del este', 'Nueva Germania', NULL),
    ('ANDRES COURIER', 'Nueva Germania', NULL),
    ('REINALDO COURIER', 'Nueva Germania', NULL),
    ('WERAHA', 'Nueva Germania', NULL),
    ('Lucero del este', 'San Estanislao', NULL),
    ('ANDRES COURIER', 'San Estanislao', NULL),
    ('REINALDO COURIER', 'San Estanislao', NULL),
    ('WERAHA', 'San Estanislao', NULL),
    ('Lucero del este', 'San Pablo', NULL),
    ('ANDRES COURIER', 'San Pablo', NULL),
    ('REINALDO COURIER', 'San Pablo', NULL),
    ('WERAHA', 'San Pablo', NULL),
    ('Lucero del este', 'San Pedro de Ycuamandyyu', NULL),
    ('ANDRES COURIER', 'San Pedro de Ycuamandyyu', NULL),
    ('REINALDO COURIER', 'San Pedro de Ycuamandyyu', NULL),
    ('WERAHA', 'San Pedro de Ycuamandyyu', NULL),
    ('Lucero del este', 'San Vicente Pancholo', NULL),
    ('ANDRES COURIER', 'San Vicente Pancholo', NULL),
    ('REINALDO COURIER', 'San Vicente Pancholo', NULL),
    ('WERAHA', 'San Vicente Pancholo', NULL),
    ('Lucero del este', 'Santa Rosa del Aguaray', NULL),
    ('ANDRES COURIER', 'Santa Rosa del Aguaray', NULL),
    ('REINALDO COURIER', 'Santa Rosa del Aguaray', NULL),
    ('WERAHA', 'Santa Rosa del Aguaray', NULL),
    ('Lucero del este', 'Tacuatí', NULL),
    ('ANDRES COURIER', 'Tacuatí', NULL),
    ('REINALDO COURIER', 'Tacuatí', NULL),
    ('WERAHA', 'Tacuatí', NULL),
    ('Lucero del este', 'Unión', NULL),
    ('ANDRES COURIER', 'Unión', NULL),
    ('REINALDO COURIER', 'Unión', NULL),
    ('WERAHA', 'Unión', NULL),
    ('Lucero del este', 'Villa del Rosario', NULL),
    ('ANDRES COURIER', 'Villa del Rosario', NULL),
    ('REINALDO COURIER', 'Villa del Rosario', NULL),
    ('WERAHA', 'Villa del Rosario', NULL),
    ('Lucero del este', 'Yataity del Norte', NULL),
    ('ANDRES COURIER', 'Yataity del Norte', NULL),
    ('REINALDO COURIER', 'Yataity del Norte', NULL),
    ('WERAHA', 'Yataity del Norte', NULL),
    ('Lucero del este', 'Yrybucuá', NULL),
    ('ANDRES COURIER', 'Yrybucuá', NULL),
    ('REINALDO COURIER', 'Yrybucuá', NULL),
    ('WERAHA', 'Yrybucuá', NULL),
    ('Lucero del este', 'San José del Rosario', NULL),
    ('ANDRES COURIER', 'San José del Rosario', NULL),
    ('REINALDO COURIER', 'San José del Rosario', NULL),
    ('WERAHA', 'San José del Rosario', NULL),
    ('Lucero del este', 'Puerto Vallemi', NULL),
    ('ANDRES COURIER', 'Puerto Vallemi', NULL),
    ('REINALDO COURIER', 'Puerto Vallemi', NULL),
    ('WERAHA', 'Puerto Vallemi', NULL),
    ('Lucero del este', 'San Ignacio', NULL),
    ('ANDRES COURIER', 'San Ignacio', NULL),
    ('REINALDO COURIER', 'San Ignacio', NULL),
    ('WERAHA', 'San Ignacio', NULL),
    ('Lucero del este', 'Maria Auxiliadora', NULL),
    ('ANDRES COURIER', 'Maria Auxiliadora', NULL),
    ('REINALDO COURIER', 'Maria Auxiliadora', NULL),
    ('WERAHA', 'Maria Auxiliadora', NULL),
    ('Lucero del este', 'Puente Kyha', 35000),
    ('ANDRES COURIER', 'Puente Kyha', NULL),
    ('REINALDO COURIER', 'Puente Kyha', NULL),
    ('WERAHA', 'Puente Kyha', NULL);

-- STEP 3: Insert into carrier_coverage for a specific store
-- Replace STORE_ID_HERE with the actual store UUID

/*
INSERT INTO carrier_coverage (store_id, carrier_id, city, rate)
SELECT
    'STORE_ID_HERE'::uuid as store_id,
    c.id as carrier_id,
    tc.city,
    tc.rate
FROM temp_carrier_coverage tc
JOIN carriers c ON c.name = tc.carrier_name AND c.store_id = 'STORE_ID_HERE'
ON CONFLICT (carrier_id, city, COALESCE(department, '')) DO UPDATE SET
    rate = EXCLUDED.rate,
    updated_at = NOW();
*/

-- Drop temp table when done
-- DROP TABLE temp_carrier_coverage;

-- Total coverage entries: 1064 (4 carriers x ~266 cities)
Shell cwd was reset to /Users/gastonlopez/Documents/Code/PRODUCTION/ORDEFY