/**
 * Ordefy email brand tokens (shared by react-email templates).
 *
 *   Primary (lime green): #b0e636
 *   Dark bg:              #09090b
 *   Card bg:              #131318
 *   Card border:          #1f1f26
 *   Text primary:         #f2f2f2
 *   Text secondary:       #9ca3af
 *   Text muted:           #6b7280
 */

export const BRAND = {
  primary: '#b0e636',
  primaryDark: '#9acd2e',
  bg: '#09090b',
  card: '#131318',
  cardBorder: '#1f1f26',
  text: '#f2f2f2',
  textSecondary: '#9ca3af',
  textMuted: '#6b7280',
  white: '#ffffff',
  divider: '#1f1f26',
  footerBg: '#060608',
} as const;

// Generated by api/scripts/generate-email-logo.tsx. Both variants are 560x160
// PNG (2x density for the 280x80 retina display target) served by the
// Vite/Vercel frontend from public/email/.
//
//   logo.png       -- transparent background, lime wordmark.
//                     Kept for legacy callers; new templates use logo-dark.
//   logo-dark.png  -- dark #09090b background baked in, lime wordmark.
//                     Bulletproof in clients that force color inversion
//                     (Gmail iOS, Outlook desktop): the logo block keeps
//                     visual weight and never produces a halo because there
//                     is no transparency for the client to repaint.
export const LOGO_URL = 'https://app.ordefy.io/email/logo.png';
export const LOGO_DARK_URL = 'https://app.ordefy.io/email/logo-dark.png';

export const APP_URL =
  process.env.APP_URL || process.env.FRONTEND_URL || 'https://app.ordefy.io';

export const SUPPORT_EMAIL = process.env.SUPPORT_EMAIL || 'soporte@ordefy.io';

export const MARKETING_URL = 'https://ordefy.io';

export const CURRENT_YEAR = new Date().getFullYear();

export const FONT_STACK =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";
