/**
 * Ordefy email brand tokens (shared by react-email templates).
 *
 *   Primary (lime green): #b0e636
 *   Dark bg:              #09090b
 *   Card bg:              #131318
 *   Card border:          #1f1f26
 *   Text primary:         #f2f2f2
 *   Text secondary:       #9ca3af
 *   Text muted:           #6b7280
 */

export const BRAND = {
  primary: '#b0e636',
  primaryDark: '#9acd2e',
  bg: '#09090b',
  card: '#131318',
  cardBorder: '#1f1f26',
  text: '#f2f2f2',
  textSecondary: '#9ca3af',
  textMuted: '#6b7280',
  white: '#ffffff',
  divider: '#1f1f26',
  footerBg: '#060608',
} as const;

// Generated by api/scripts/generate-email-logo.tsx. Transparent PNG, 560x160,
// ~8KB. The path is served by the Vite/Vercel frontend from public/email/.
export const LOGO_URL = 'https://app.ordefy.io/email/logo.png';

export const APP_URL =
  process.env.APP_URL || process.env.FRONTEND_URL || 'https://app.ordefy.io';

export const SUPPORT_EMAIL = process.env.SUPPORT_EMAIL || 'soporte@ordefy.io';

export const MARKETING_URL = 'https://ordefy.io';

export const CURRENT_YEAR = new Date().getFullYear();

export const FONT_STACK =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";
